// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/docs/proxy/document` | (string & {});
};

export type Action = {
  type?: TypeEnum;
  userid?: string;
};

export type Callback = {
  actions?: Array<Action>;
  changesurl?: string;
  filetype?: string;
  forcesavetype?: ForcesavetypeEnum;
  formsdataurl?: string;
  history?: History;
  key?: string;
  status?: StatusEnum;
  url?: string;
  users?: Array<string>;
  token?: string;
};

export type History = {
  serverVersion?: string;
  changes?: Array<{
    [key: string]: unknown;
  }>;
};

export type DocumentUploadInitRequest = {
  resourceId?: string;
  filename: string;
  extension: string;
  md5: string;
  expectedSize: number;
};

export type DocumentUploadInitResponse = {
  documentId?: string;
  putUrl?: string;
  callbackHeader?: string;
  objectKey?: string;
  flashUploaded?: boolean;
};

export type RDocumentUploadInitResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: DocumentUploadInitResponse;
};

export type DocumentStatus = {
  status?: StatusEnum2;
  errorMessage?: string;
};

export type RDocumentStatus = {
  code?: number;
  key?: string;
  msg?: string;
  data?: DocumentStatus;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type DocumentForkRequest = {
  resourceId: string;
  forkedResourceVersion?: number;
  forkedResourceName?: string;
};

export type RString = {
  code?: number;
  key?: string;
  msg?: string;
  data?: string;
};

export type DocumentCreateRequest = {
  title: string;
  resourceType: ResourceTypeEnum;
};

export type Anonymous = {
  request?: boolean;
  label?: string;
};

export type Close = {
  visible?: boolean;
  text?: string;
};

export type CoEditing = {
  mode?: ModeEnum;
  change?: boolean;
};

export type CommentGroups = {
  edit?: Array<string>;
  remove?: Array<string>;
  view?: Array<string>;
};

export type Config = {
  documentType?: DocumentTypeEnum;
  height?: string;
  token?: string;
  type?: TypeEnum2;
  width?: string;
  editorConfig?: EditorConfig;
  document?: Document;
};

export type Customer = {
  address?: string;
  info?: string;
  logo?: string;
  logoDark?: string;
  mail?: string;
  name?: string;
  phone?: string;
  www?: string;
};

export type Customization = {
  anonymous?: Anonymous;
  autosave?: boolean;
  /**
   * @deprecated
   */
  chat?: boolean;
  close?: Close;
  /**
   * @deprecated
   */
  commentAuthorOnly?: boolean;
  comments?: boolean;
  compactHeader?: boolean;
  compactToolbar?: boolean;
  compatibleFeatures?: boolean;
  customer?: Customer;
  features?: Features;
  feedback?: boolean;
  forcesave?: boolean;
  forceWesternFontSize?: boolean;
  goback?: Goback;
  help?: boolean;
  hideNotes?: boolean;
  hideRightMenu?: boolean;
  hideRulers?: boolean;
  integrationMode?: string;
  logo?: Logo;
  macros?: boolean;
  macrosMode?: MacrosModeEnum;
  mentionShare?: boolean;
  mobile?: Mobile;
  /**
   * @deprecated
   */
  mobileForceView?: boolean;
  plugins?: boolean;
  pointerMode?: string;
  review?: Review;
  reviewDisplay?: ReviewDisplayEnum;
  showHorizontalScroll?: boolean;
  /**
   * @deprecated
   */
  showReviewChanges?: boolean;
  showVerticalScroll?: boolean;
  slidePlayerBackground?: string;
  /**
   * @deprecated
   */
  spellcheck?: boolean;
  submitForm?: {
    [key: string]: unknown;
  };
  toolbarHideFileName?: boolean;
  /**
   * @deprecated
   */
  toolbarNoTabs?: boolean;
  /**
   * @deprecated
   */
  trackChanges?: boolean;
  uiTheme?: string;
  unit?: UnitEnum;
  wordHeadingsColor?: string;
  zoom?: number;
};

export type Document = {
  fileType?: string;
  key?: string;
  referenceData?: ReferenceData;
  title?: string;
  url?: string;
  info?: Info;
  permissions?: Permissions;
};

export type EditorConfig = {
  actionLink?: {
    [key: string]: unknown;
  };
  callbackUrl?: string;
  coEditing?: CoEditing;
  createUrl?: string;
  lang?: string;
  /**
   * @deprecated
   */
  location?: string;
  mode?: ModeEnum2;
  recent?: Array<Recent>;
  region?: string;
  templates?: Array<Template>;
  user?: User;
  customization?: Customization;
  embedded?: Embedded;
  plugins?: Plugins;
};

export type Embedded = {
  embedUrl?: string;
  fullscreenUrl?: string;
  saveUrl?: string;
  shareUrl?: string;
  toolbarDocked?: ToolbarDockedEnum;
};

export type Features = {
  featuresTips?: boolean;
  roles?: boolean;
  spellcheck?: boolean;
  tabBackground?: {
    [key: string]: unknown;
  };
  tabStyle?: {
    [key: string]: unknown;
  };
};

export type Goback = {
  blank?: boolean;
  /**
   * @deprecated
   */
  requestClose?: boolean;
  text?: string;
  url?: string;
};

export type Info = {
  /**
   * @deprecated
   */
  author?: string;
  /**
   * @deprecated
   */
  created?: string;
  favorite?: boolean;
  folder?: string;
  owner?: string;
  sharingSettings?: Array<SharingSettings>;
  uploaded?: string;
};

export type Logo = {
  image?: string;
  imageDark?: string;
  imageLight?: string;
  /**
   * @deprecated
   */
  imageEmbedded?: string;
  url?: string;
};

export type Mobile = {
  forceView?: boolean;
  info?: boolean;
  standardView?: boolean;
};

export type OnlyOfficeEditorConfigResponse = {
  sessionId?: string;
  config?: Config;
};

export type Permissions = {
  chat?: boolean;
  comment?: boolean;
  commentGroups?: CommentGroups;
  copy?: boolean;
  deleteCommentAuthorOnly?: boolean;
  download?: boolean;
  edit?: boolean;
  editCommentAuthorOnly?: boolean;
  fillForms?: boolean;
  modifyContentControl?: boolean;
  modifyFilter?: boolean;
  print?: boolean;
  protect?: boolean;
  /**
   * @deprecated
   */
  rename?: boolean;
  review?: boolean;
  reviewGroups?: Array<string>;
  userInfoGroups?: Array<string>;
};

export type Plugins = {
  autostart?: Array<string>;
  pluginsData?: Array<string>;
  disable?: Array<string>;
};

export type ROnlyOfficeEditorConfigResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: OnlyOfficeEditorConfigResponse;
};

export type Recent = {
  folder?: string;
  title?: string;
  url?: string;
};

export type ReferenceData = {
  fileKey?: string;
  instanceId?: string;
  key?: string;
};

export type Review = {
  hideReviewDisplay?: boolean;
  hoverMode?: boolean;
  reviewDisplay?: ReviewDisplayEnum;
  showReviewChanges?: boolean;
  trackChanges?: boolean;
};

export type SharingSettings = {
  isLink?: boolean;
  permissions?: PermissionsEnum;
  user?: string;
};

export type Template = {
  image?: string;
  title?: string;
  url?: string;
};

export type User = {
  id?: string;
  name?: string;
  group?: string;
  image?: string;
  roles?: Array<string>;
};

export type DocumentUploadMeta = {
  documentName?: string;
  uploaderId?: number;
  fileType?: ResourceTypeEnum;
  size?: number;
};

export type DocumentVersionBase = {
  uploadMeta?: DocumentUploadMeta;
  documentStatus?: DocumentStatus;
  maxPreviewPages?: number;
};

export type RListDocumentVersionBase = {
  code?: number;
  key?: string;
  msg?: string;
  data?: Array<DocumentVersionBase>;
};

export type DocumentVersionInfoResponse = {
  uploadMeta?: DocumentUploadMeta;
  documentStatus?: DocumentStatus;
  maxPreviewPages?: number;
  version?: number;
};

export type PageRDocumentVersionInfoResponse = {
  list?: Array<DocumentVersionInfoResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRDocumentVersionInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRDocumentVersionInfoResponse;
};

export type DocumentInfoResponse = {
  resourceInfo?: ResourceItemResponse;
  documentVersionInfo?: DocumentVersionInfoResponse;
  authorsDisplay?: {
    [key: string]: UserDisplayBase;
  };
};

export type MarketSaleInfoResponse = {
  reviewActions?: Array<ItemsEnum>;
  reviewContentPercentage?: number;
  marketSaleTiers?: Array<MarketSaleTierResponse>;
  status?: StatusEnum3;
  offerVersion?: number;
  auditMessage?: string;
  auditAt?: string;
};

export type MarketSaleTierResponse = {
  offerId?: string;
  grantedActions?: Array<ItemsEnum>;
  price?: number;
};

export type RDocumentInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: DocumentInfoResponse;
};

export type ResourceInteractionInfoBase = {
  readCount?: number;
  likeCount?: number;
  scoreCount?: number;
  scoreTotal?: number;
  favoriteCount?: number;
  commentCount?: number;
};

export type ResourceItemResponse = {
  resourceName?: string;
  resourceType?: ResourceTypeEnum;
  ownerId?: string;
  preview?: string;
  size?: number;
  resourceInteractionInfo?: ResourceInteractionInfoBase;
  resourceId?: string;
  ownerInfo?: UserDisplayBase;
  currentTags?: {
    [key: string]: TagInfoBase;
  };
  currentActions?: Array<ItemsEnum>;
  overrideGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
  marketSaleInfos?: {
    [key: string]: MarketSaleInfoResponse;
  };
};

export type TagInfoBase = {
  groupId?: string;
  tagName?: string;
  tagDesc?: string;
  tagIcon?: string;
  tagColor?: string;
  tagCreator?: string;
  isPath?: boolean;
};

export type UserDisplayBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: IdentityTypeEnum;
};

export const TypeEnum = {
  0: '0',
  1: '1',
  2: '2',
} as const;

export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];

export const ForcesavetypeEnum = {
  0: '0',
  1: '1',
  2: '2',
  3: '3',
} as const;

export type ForcesavetypeEnum = (typeof ForcesavetypeEnum)[keyof typeof ForcesavetypeEnum];

export const StatusEnum = {
  1: '1',
  2: '2',
  3: '3',
  4: '4',
  6: '6',
  7: '7',
} as const;

export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];

export const StatusEnum2 = {
  UPLOADING: 'UPLOADING',
  UPLOADED: 'UPLOADED',
  CONVERTING_AND_PARSING: 'CONVERTING_AND_PARSING',
  REGISTERING_RES: 'REGISTERING_RES',
  READY: 'READY',
  TRANSFER_TIMEOUT: 'TRANSFER_TIMEOUT',
  REGISTERING_RES_TIMEOUT: 'REGISTERING_RES_TIMEOUT',
  FAILED: 'FAILED',
} as const;

export type StatusEnum2 = (typeof StatusEnum2)[keyof typeof StatusEnum2];

export const ResourceTypeEnum = {
  NOTE: 'NOTE',
  DRAWIO: 'DRAWIO',
  PDF: 'PDF',
  DOC: 'DOC',
  DOCX: 'DOCX',
  PPT: 'PPT',
  PPTX: 'PPTX',
  XLS: 'XLS',
  XLSX: 'XLSX',
  SKILL: 'SKILL',
  AGENT: 'AGENT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ResourceTypeEnum = (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];

export const ModeEnum = { FAST: 'fast', STRICT: 'strict' } as const;

export type ModeEnum = (typeof ModeEnum)[keyof typeof ModeEnum];

export const DocumentTypeEnum = {
  WORD: 'word',
  CELL: 'cell',
  SLIDE: 'slide',
  PDF: 'pdf',
  DIAGRAM: 'diagram',
} as const;

export type DocumentTypeEnum = (typeof DocumentTypeEnum)[keyof typeof DocumentTypeEnum];

export const TypeEnum2 = {
  DESKTOP: 'desktop',
  MOBILE: 'mobile',
  EMBEDDED: 'embedded',
} as const;

export type TypeEnum2 = (typeof TypeEnum2)[keyof typeof TypeEnum2];

export const MacrosModeEnum = {
  DISABLE: 'disable',
  ENABLE: 'enable',
  WARN: 'warn',
} as const;

export type MacrosModeEnum = (typeof MacrosModeEnum)[keyof typeof MacrosModeEnum];

/**
 * @deprecated
 */
export const ReviewDisplayEnum = {
  MARKUP: 'markup',
  SIMPLE: 'simple',
  FINAL: 'final',
  ORIGINAL: 'original',
} as const;

/**
 * @deprecated
 */
export type ReviewDisplayEnum = (typeof ReviewDisplayEnum)[keyof typeof ReviewDisplayEnum];

export const UnitEnum = {
  CM: 'cm',
  PT: 'pt',
  INCH: 'inch',
} as const;

export type UnitEnum = (typeof UnitEnum)[keyof typeof UnitEnum];

export const ModeEnum2 = { VIEW: 'view', EDIT: 'edit' } as const;

export type ModeEnum2 = (typeof ModeEnum2)[keyof typeof ModeEnum2];

export const ToolbarDockedEnum = { TOP: 'top', BOTTOM: 'bottom' } as const;

export type ToolbarDockedEnum = (typeof ToolbarDockedEnum)[keyof typeof ToolbarDockedEnum];

export const PermissionsEnum = {
  FULL_ACCESS: 'Full Access',
  READ_ONLY: 'Read Only',
  DENY_ACCESS: 'Deny Access',
} as const;

export type PermissionsEnum = (typeof PermissionsEnum)[keyof typeof PermissionsEnum];

export const ItemsEnum = {
  DISCOVER: 'DISCOVER',
  VIEW: 'VIEW',
  LOAD: 'LOAD',
  EDIT: 'EDIT',
  INLINE_COMMENT: 'INLINE_COMMENT',
  DOWNLOAD_WATERMARK: 'DOWNLOAD_WATERMARK',
  DOWNLOAD_ORIGINAL: 'DOWNLOAD_ORIGINAL',
  FORK: 'FORK',
  COMMENT: 'COMMENT',
} as const;

export type ItemsEnum = (typeof ItemsEnum)[keyof typeof ItemsEnum];

export const StatusEnum3 = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
  BANNED: 'BANNED',
  OFF_SHELF: 'OFF_SHELF',
} as const;

export type StatusEnum3 = (typeof StatusEnum3)[keyof typeof StatusEnum3];

export const IdentityTypeEnum = {
  1: '1',
  2: '2',
  3: '3',
} as const;

export type IdentityTypeEnum = (typeof IdentityTypeEnum)[keyof typeof IdentityTypeEnum];

export type CallbackData = {
  body: Callback;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/external/document/onlyoffice/callback/{sessionId}';
};

export type CallbackResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: number;
  };
};

export type CallbackResponse = CallbackResponses[keyof CallbackResponses];

export type UploadDocData = {
  body: DocumentUploadInitRequest;
  path?: never;
  query?: never;
  url: '/document/uploadDoc';
};

export type UploadDocResponses = {
  /**
   * OK
   */
  200: RDocumentUploadInitResponse;
};

export type UploadDocResponse = UploadDocResponses[keyof UploadDocResponses];

export type SyncDocStatusData = {
  body?: never;
  path?: never;
  query: {
    documentId: string;
  };
  url: '/document/syncDocStatus';
};

export type SyncDocStatusResponses = {
  /**
   * OK
   */
  200: RDocumentStatus;
};

export type SyncDocStatusResponse = SyncDocStatusResponses[keyof SyncDocStatusResponses];

export type RetryDocProcessData = {
  body?: never;
  path?: never;
  query: {
    documentId: string;
  };
  url: '/document/retryDocProcess';
};

export type RetryDocProcessResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type RetryDocProcessResponse = RetryDocProcessResponses[keyof RetryDocProcessResponses];

export type ForkDocumentData = {
  body: DocumentForkRequest;
  path?: never;
  query?: never;
  url: '/document/forkDocument';
};

export type ForkDocumentResponses = {
  /**
   * OK
   */
  200: RString;
};

export type ForkDocumentResponse = ForkDocumentResponses[keyof ForkDocumentResponses];

export type CancelDocProcessData = {
  body?: never;
  path?: never;
  query: {
    documentId: string;
  };
  url: '/document/cancelDocProcess';
};

export type CancelDocProcessResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type CancelDocProcessResponse = CancelDocProcessResponses[keyof CancelDocProcessResponses];

export type CreateDocumentData = {
  body: DocumentCreateRequest;
  path?: never;
  query?: never;
  url: '/document/addDocument';
};

export type CreateDocumentResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateDocumentResponse = CreateDocumentResponses[keyof CreateDocumentResponses];

export type GetEditorConfigData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
  };
  url: '/document/onlyoffice/editorConfig';
};

export type GetEditorConfigResponses = {
  /**
   * OK
   */
  200: ROnlyOfficeEditorConfigResponse;
};

export type GetEditorConfigResponse = GetEditorConfigResponses[keyof GetEditorConfigResponses];

export type ListPendingDocsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/document/listPendingDocs';
};

export type ListPendingDocsResponses = {
  /**
   * OK
   */
  200: RListDocumentVersionBase;
};

export type ListPendingDocsResponse = ListPendingDocsResponses[keyof ListPendingDocsResponses];

export type ListDocumentVersionsData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    page?: number;
    size?: number;
  };
  url: '/document/listDocVersions';
};

export type ListDocumentVersionsResponses = {
  /**
   * OK
   */
  200: RPageRDocumentVersionInfoResponse;
};

export type ListDocumentVersionsResponse =
  ListDocumentVersionsResponses[keyof ListDocumentVersionsResponses];

export type PreviewDocumentData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    targetVersion?: number;
  };
  url: '/document/getDocPreview';
};

export type PreviewDocumentResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetDocumentInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    targetVersion?: number;
  };
  url: '/document/getDocInfo';
};

export type GetDocumentInfoResponses = {
  /**
   * OK
   */
  200: RDocumentInfoResponse;
};

export type GetDocumentInfoResponse = GetDocumentInfoResponses[keyof GetDocumentInfoResponses];
