// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://172.28.0.29:19906' | (string & {});
};

export type DocumentUploadInitRequest = {
  filename: string;
  extension: string;
  md5: string;
  expectedSize: number;
};

export type DocumentUploadInitResponse = {
  documentId?: string;
  putUrl?: string;
  callbackHeader?: string;
  objectKey?: string;
  flashUploaded?: boolean;
};

export type RDocumentUploadInitResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: DocumentUploadInitResponse;
};

export type DocumentStatus = {
  status?: StatusEnum;
  errorMessage?: string;
};

export type RDocumentStatus = {
  code?: number;
  key?: string;
  msg?: string;
  data?: DocumentStatus;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type DocumentInfoBase = {
  uploadMeta?: DocumentUploadMeta;
  documentStatus?: DocumentStatus;
  maxPreviewPages?: number;
};

export type DocumentUploadMeta = {
  documentName?: string;
  uploaderId?: number;
  fileType?: FileTypeEnum;
  size?: number;
};

export type RListDocumentInfoBase = {
  code?: number;
  key?: string;
  msg?: string;
  data?: Array<DocumentInfoBase>;
};

export type DocumentInfoResponse = {
  resourceInfo?: ResourceItemResponse;
  documentInfo?: DocumentInfoBase;
};

export type RDocumentInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: DocumentInfoResponse;
};

export type ResourceInteractionInfoBase = {
  readCount?: number;
  likeCount?: number;
  scoreCount?: number;
  scoreTotal?: number;
};

export type ResourceItemResponse = {
  resourceName?: string;
  resourceType?: FileTypeEnum;
  ownerId?: string;
  preview?: string;
  size?: number;
  resourceId?: string;
  ownerInfo?: UserDisplayBase;
  resourceInteractionInfo?: ResourceInteractionInfoBase;
  currentTags?: {
    [key: string]: string;
  };
  currentActions?: Array<ItemsEnum>;
  overrideGrantedActions?: Array<ItemsEnum>;
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
};

export type UserDisplayBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: IdentityTypeEnum;
};

export const StatusEnum = {
  UPLOADING: 'UPLOADING',
  UPLOADED: 'UPLOADED',
  CONVERTING_AND_PARSING: 'CONVERTING_AND_PARSING',
  REGISTERING_RES: 'REGISTERING_RES',
  READY: 'READY',
  TRANSFER_TIMEOUT: 'TRANSFER_TIMEOUT',
  REGISTERING_RES_TIMEOUT: 'REGISTERING_RES_TIMEOUT',
  FAILED: 'FAILED',
} as const;

export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];

export const FileTypeEnum = {
  NOTE: 'NOTE',
  PDF: 'PDF',
  DOC: 'DOC',
  DOCX: 'DOCX',
  PPT: 'PPT',
  PPTX: 'PPTX',
  XLS: 'XLS',
  XLSX: 'XLSX',
  SKILL: 'SKILL',
  AGENT: 'AGENT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type FileTypeEnum = (typeof FileTypeEnum)[keyof typeof FileTypeEnum];

export const ItemsEnum = {
  DISCOVER: 'DISCOVER',
  VIEW: 'VIEW',
  EDIT: 'EDIT',
  DOWNLOAD_WATERMARK: 'DOWNLOAD_WATERMARK',
  DOWNLOAD_ORIGINAL: 'DOWNLOAD_ORIGINAL',
} as const;

export type ItemsEnum = (typeof ItemsEnum)[keyof typeof ItemsEnum];

export const IdentityTypeEnum = {
  1: '1',
  2: '2',
  3: '3',
} as const;

export type IdentityTypeEnum = (typeof IdentityTypeEnum)[keyof typeof IdentityTypeEnum];

export type UploadDocData = {
  body: DocumentUploadInitRequest;
  path?: never;
  query?: never;
  url: '/document/uploadDoc';
};

export type UploadDocResponses = {
  /**
   * OK
   */
  200: RDocumentUploadInitResponse;
};

export type UploadDocResponse = UploadDocResponses[keyof UploadDocResponses];

export type SyncDocStatusData = {
  body?: never;
  path?: never;
  query: {
    documentId: string;
  };
  url: '/document/syncDocStatus';
};

export type SyncDocStatusResponses = {
  /**
   * OK
   */
  200: RDocumentStatus;
};

export type SyncDocStatusResponse = SyncDocStatusResponses[keyof SyncDocStatusResponses];

export type RetryDocProcessData = {
  body?: never;
  path?: never;
  query: {
    documentId: string;
  };
  url: '/document/retryDocProcess';
};

export type RetryDocProcessResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type RetryDocProcessResponse = RetryDocProcessResponses[keyof RetryDocProcessResponses];

export type CancelDocProcessData = {
  body?: never;
  path?: never;
  query: {
    documentId: string;
  };
  url: '/document/cancelDocProcess';
};

export type CancelDocProcessResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type CancelDocProcessResponse = CancelDocProcessResponses[keyof CancelDocProcessResponses];

export type ListPendingDocsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/document/listPendingDocs';
};

export type ListPendingDocsResponses = {
  /**
   * OK
   */
  200: RListDocumentInfoBase;
};

export type ListPendingDocsResponse = ListPendingDocsResponses[keyof ListPendingDocsResponses];

export type PreviewDocumentData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
  };
  url: '/document/getDocPreview';
};

export type PreviewDocumentResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetNoteInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
  };
  url: '/document/getDocInfo';
};

export type GetNoteInfoResponses = {
  /**
   * OK
   */
  200: RDocumentInfoResponse;
};

export type GetNoteInfoResponse = GetNoteInfoResponses[keyof GetNoteInfoResponses];
