// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/docs/proxy/resource` | (string & {});
};

export type TagDeleteRequest = {
  groupId?: string;
  targetTagId: string;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type TagMoveRequest = {
  groupId?: string;
  targetTagId: string;
  newParentId?: string;
};

export type TagUpdateRequest = {
  groupId?: string;
  tagName?: string;
  tagDesc?: string;
  tagIcon?: string;
  tagColor?: string;
  tagCreator?: string;
  isPath?: boolean;
  taggedResourceAclGrantScope?: TaggedResourceAclGrantScopeEnum;
  taggedResourceAclGrantSpecifiedUsers?: Array<string>;
  taggedResourceGrantedActionsMask?: number;
  tagMountPermissionScope?: TaggedResourceAclGrantScopeEnum;
  tagMountSpecifiedUsers?: Array<string>;
  targetTagId: string;
  grantedActions?: Array<ItemsEnum>;
};

export type TagCreateRequest = {
  groupId?: string;
  parentId?: string;
  tagName: string;
  tagDesc?: string;
  taggedResourceAclGrantScope?: TaggedResourceAclGrantScopeEnum;
  taggedResourceAclGrantSpecifiedUsers?: Array<string>;
  grantedActions?: Array<ItemsEnum>;
  tagMountPermissionScope?: TaggedResourceAclGrantScopeEnum;
  tagMountSpecifiedUsers?: Array<string>;
};

export type RString = {
  code?: number;
  key?: string;
  msg?: string;
  data?: string;
};

export type MarketPurchaseRequest = {
  offerId: string;
  resourceId: string;
  marketGroupId: string;
};

export type MarketOrderResponse = {
  traceId?: string;
  buyerId?: string;
  sellerId?: string;
  purchasedResourceId?: string;
  purchasedOfferVersion?: number;
  marketGroupId?: string;
  buyerGrantedActionsMask?: number;
  buyerPaidPrice?: number;
  orderId?: string;
  createTime?: string;
  updateTime?: string;
};

export type RMarketOrderResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: MarketOrderResponse;
};

export type MarketSalePublishRequest = {
  resourceId: string;
  marketGroupId: string;
  tagIds: Array<string>;
  reviewContentPercentage?: number;
  reviewActions?: Array<ItemsEnum>;
  marketSaleTiers: Array<MarketSaleTier>;
  offerVersion: number;
};

export type MarketSaleTier = {
  grantedActions: Array<ItemsEnum>;
  price: number;
};

export type MarketSaleOffShelfRequest = {
  resourceId: string;
  marketGroupId: string;
};

export type ResourceRenameRequest = {
  resourceId: string;
  newName: string;
};

export type ResourceUpdateTagsRequest = {
  resourceId: string;
  groupId?: string;
  tagIds: Array<string>;
};

export type ResourceUpdateActionPermissionRequest = {
  resourceId: string;
  overrideGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
};

export type ResourceLikeRequest = {
  resourceId: string;
};

export type ResourceReadRequest = {
  resourceId: string;
};

export type ResourceRateRequest = {
  resourceId: string;
  score: number;
};

export type GroupResConfigUpdateRequest = {
  groupId: string;
  fileOrgLogic: FileOrgLogicEnum;
  defaultMemberActions?: Array<ItemsEnum>;
};

export type FavoriteCollectionInfoUpdateRequest = {
  collectionId: string;
  collectionName: string;
  description?: string;
};

export type FavoriteCollectionDeleteRequest = {
  collectionId: string;
  keepResourcesToDefault?: boolean;
};

export type FavoriteCollectionCreateRequest = {
  collectionName: string;
  description?: string;
};

export type ResourceFavoriteRequest = {
  resourceId: string;
  favorite: boolean;
  collectionIds?: Array<string>;
};

export type CommentLikeRequest = {
  resourceId: string;
  commentId: string;
};

export type RBoolean = {
  code?: number;
  key?: string;
  msg?: string;
  data?: boolean;
};

export type CommentDeleteRequest = {
  resourceId: string;
  commentId: string;
};

export type CommentReplyCreateRequest = {
  resourceId: string;
  replyTo: string;
  content: string;
  imageUrls?: Array<string>;
};

export type CommentCreateRequest = {
  resourceId: string;
  content: string;
  imageUrls?: Array<string>;
};

export type MarketSaleInfoResponse = {
  reviewActions?: Array<ItemsEnum>;
  reviewContentPercentage?: number;
  marketSaleTiers?: Array<MarketSaleTierResponse>;
  status?: StatusEnum;
  offerVersion?: number;
  auditMessage?: string;
  auditAt?: string;
};

export type MarketSaleTierResponse = {
  offerId?: string;
  grantedActions?: Array<ItemsEnum>;
  price?: number;
};

export type ResourceInteractionInfoBase = {
  readCount?: number;
  likeCount?: number;
  scoreCount?: number;
  scoreTotal?: number;
  favoriteCount?: number;
  commentCount?: number;
};

export type ResourceItemResponse = {
  resourceName?: string;
  resourceType?: ResourceTypeEnum;
  ownerId?: string;
  preview?: string;
  size?: number;
  resourceInteractionInfo?: ResourceInteractionInfoBase;
  resourceId?: string;
  ownerInfo?: UserDisplayBase;
  currentTags?: {
    [key: string]: TagInfoBase;
  };
  currentActions?: Array<ItemsEnum>;
  overrideGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
  marketSaleInfos?: {
    [key: string]: MarketSaleInfoResponse;
  };
};

export type TagInfoBase = {
  groupId?: string;
  tagName?: string;
  tagDesc?: string;
  tagIcon?: string;
  tagColor?: string;
  tagCreator?: string;
  isPath?: boolean;
};

export type UserDisplayBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: IdentityTypeEnum;
};

export type MarketSaleAuditRequest = {
  resourceId: string;
  marketGroupId: string;
  status: StatusEnum;
  offerVersion: number;
  auditMessage?: string;
};

export type RListTagTreeResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: Array<TagTreeResponse>;
};

export type TagTreeResponse = {
  groupId?: string;
  tagName?: string;
  tagDesc?: string;
  tagIcon?: string;
  tagColor?: string;
  tagCreator?: string;
  isPath?: boolean;
  taggedResourceAclGrantScope?: TaggedResourceAclGrantScopeEnum;
  taggedResourceAclGrantSpecifiedUsers?: Array<string>;
  taggedResourceGrantedActionsMask?: number;
  tagMountPermissionScope?: TaggedResourceAclGrantScopeEnum;
  tagMountSpecifiedUsers?: Array<string>;
  tagId?: string;
  parentId?: string;
  grantedActions?: Array<ItemsEnum>;
};

export type PageRSearchHitItemResponse = {
  list?: Array<SearchHitItemResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRSearchHitItemResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRSearchHitItemResponse;
};

export type SearchHitItemResponse = {
  resourceId?: string;
  resourceType?: ResourceTypeEnum;
  resourceName?: string;
  highlightContent?: string;
  updateTime?: string;
};

export type PageRMarketOrderResponse = {
  list?: Array<MarketOrderResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRMarketOrderResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRMarketOrderResponse;
};

export type PageRResourceItemResponse = {
  list?: Array<ResourceItemResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRResourceItemResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRResourceItemResponse;
};

export type RResourceUserInteractionRecordResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: ResourceUserInteractionRecordResponse;
};

export type ResourceUserInteractionRecordResponse = {
  read?: boolean;
  liked?: boolean;
  score?: number;
  likedCommentIds?: Array<string>;
  resourceId?: string;
};

export type GroupResConfigResponse = {
  groupId?: string;
  fileOrgLogic?: FileOrgLogicEnum;
  defaultMemberActions?: Array<ItemsEnum>;
};

export type RGroupResConfigResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: GroupResConfigResponse;
};

export type FavoriteItemResponse = {
  resourceId?: string;
  resourceInfo?: ResourceItemResponse;
  favoritedAt?: string;
  collectionIds?: Array<string>;
  accessible?: boolean;
};

export type PageRFavoriteItemResponse = {
  list?: Array<FavoriteItemResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRFavoriteItemResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRFavoriteItemResponse;
};

export type FavoriteCollectionResponse = {
  collectionName?: string;
  description?: string;
  isDefault?: boolean;
  collectionId?: string;
  itemCount?: number;
  createTime?: string;
};

export type RListFavoriteCollectionResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: Array<FavoriteCollectionResponse>;
};

export type RResourceFavoriteStatusResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: ResourceFavoriteStatusResponse;
};

export type ResourceFavoriteStatusResponse = {
  collectionIds?: Array<string>;
};

export type PageRResourceCommentItemResponse = {
  list?: Array<ResourceCommentItemResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRResourceCommentItemResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRResourceCommentItemResponse;
};

export type ResourceCommentItemResponse = {
  resourceId?: string;
  replyToUserId?: string;
  authorId?: string;
  content?: string;
  imageUrls?: Array<string>;
  likeCount?: number;
  replyCount?: number;
  commentType?: CommentTypeEnum;
  commentId?: string;
  authorInfo?: UserDisplayBase;
  replyToUserInfo?: UserDisplayBase;
  createTime?: number;
  deleted?: boolean;
};

export const SchemaEnum = {
  ALL: 'ALL',
  DOCUMENT: 'DOCUMENT',
  NOTE: 'NOTE',
} as const;

export type SchemaEnum = (typeof SchemaEnum)[keyof typeof SchemaEnum];

export const SchemaEnum2 = { AND: 'AND', OR: 'OR' } as const;

export type SchemaEnum2 = (typeof SchemaEnum2)[keyof typeof SchemaEnum2];

export const SchemaEnum3 = {
  UPDATE_TIME: 'UPDATE_TIME',
  CREATE_TIME: 'CREATE_TIME',
  NAME: 'NAME',
  SIZE: 'SIZE',
} as const;

export type SchemaEnum3 = (typeof SchemaEnum3)[keyof typeof SchemaEnum3];

export const SchemaEnum4 = { ASC: 'ASC', DESC: 'DESC' } as const;

export type SchemaEnum4 = (typeof SchemaEnum4)[keyof typeof SchemaEnum4];

export const SchemaEnum5 = { CREATE_TIME: 'CREATE_TIME', LIKE_COUNT: 'LIKE_COUNT' } as const;

export type SchemaEnum5 = (typeof SchemaEnum5)[keyof typeof SchemaEnum5];

export const TaggedResourceAclGrantScopeEnum = {
  ALL: 'ALL',
  ONLY_ADMIN: 'ONLY_ADMIN',
  WHITELIST: 'WHITELIST',
  BLACKLIST: 'BLACKLIST',
} as const;

export type TaggedResourceAclGrantScopeEnum =
  (typeof TaggedResourceAclGrantScopeEnum)[keyof typeof TaggedResourceAclGrantScopeEnum];

export const ItemsEnum = {
  DISCOVER: 'DISCOVER',
  VIEW: 'VIEW',
  LOAD: 'LOAD',
  EDIT: 'EDIT',
  INLINE_COMMENT: 'INLINE_COMMENT',
  DOWNLOAD_WATERMARK: 'DOWNLOAD_WATERMARK',
  DOWNLOAD_ORIGINAL: 'DOWNLOAD_ORIGINAL',
  FORK: 'FORK',
  COMMENT: 'COMMENT',
} as const;

export type ItemsEnum = (typeof ItemsEnum)[keyof typeof ItemsEnum];

export const FileOrgLogicEnum = { FOLDER: 'FOLDER', TAG: 'TAG' } as const;

export type FileOrgLogicEnum = (typeof FileOrgLogicEnum)[keyof typeof FileOrgLogicEnum];

export const StatusEnum = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
  BANNED: 'BANNED',
  OFF_SHELF: 'OFF_SHELF',
} as const;

export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];

export const ResourceTypeEnum = {
  NOTE: 'NOTE',
  DRAWIO: 'DRAWIO',
  PDF: 'PDF',
  DOC: 'DOC',
  DOCX: 'DOCX',
  PPT: 'PPT',
  PPTX: 'PPTX',
  XLS: 'XLS',
  XLSX: 'XLSX',
  SKILL: 'SKILL',
  AGENT: 'AGENT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ResourceTypeEnum = (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];

export const IdentityTypeEnum = {
  1: '1',
  2: '2',
  3: '3',
} as const;

export type IdentityTypeEnum = (typeof IdentityTypeEnum)[keyof typeof IdentityTypeEnum];

export const CommentTypeEnum = {
  COMMENT: 'COMMENT',
  REPLY_TO_COMMENT: 'REPLY_TO_COMMENT',
  REPLY_TO_REPLY: 'REPLY_TO_REPLY',
} as const;

export type CommentTypeEnum = (typeof CommentTypeEnum)[keyof typeof CommentTypeEnum];

export type DeleteTagData = {
  body: TagDeleteRequest;
  path?: never;
  query?: never;
  url: '/resource/tag/removeTag';
};

export type DeleteTagResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type MoveTagData = {
  body: TagMoveRequest;
  path?: never;
  query?: never;
  url: '/resource/tag/moveTag';
};

export type MoveTagResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type MoveTagResponse = MoveTagResponses[keyof MoveTagResponses];

export type UpdateTagData = {
  body: TagUpdateRequest;
  path?: never;
  query?: never;
  url: '/resource/tag/changeTag';
};

export type UpdateTagResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateTagResponse = UpdateTagResponses[keyof UpdateTagResponses];

export type CreateTagData = {
  body: TagCreateRequest;
  path?: never;
  query?: never;
  url: '/resource/tag/addTag';
};

export type CreateTagResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type PurchaseResourceData = {
  body: MarketPurchaseRequest;
  path?: never;
  query?: never;
  url: '/resource/market/purchaseResource';
};

export type PurchaseResourceResponses = {
  /**
   * OK
   */
  200: RMarketOrderResponse;
};

export type PurchaseResourceResponse = PurchaseResourceResponses[keyof PurchaseResourceResponses];

export type PublishSaleInfoData = {
  body: MarketSalePublishRequest;
  path?: never;
  query?: never;
  url: '/resource/market/publishSaleInfo';
};

export type PublishSaleInfoResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type PublishSaleInfoResponse = PublishSaleInfoResponses[keyof PublishSaleInfoResponses];

export type OffShelfSaleInfoData = {
  body: MarketSaleOffShelfRequest;
  path?: never;
  query?: never;
  url: '/resource/market/offShelfSaleInfo';
};

export type OffShelfSaleInfoResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type OffShelfSaleInfoResponse = OffShelfSaleInfoResponses[keyof OffShelfSaleInfoResponses];

export type RenameResourceData = {
  body: ResourceRenameRequest;
  path?: never;
  query?: never;
  url: '/resource/item/renameResource';
};

export type RenameResourceResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type RenameResourceResponse = RenameResourceResponses[keyof RenameResourceResponses];

export type DeleteResourceData = {
  body?: never;
  path?: never;
  query: {
    resourceIds: Array<string>;
  };
  url: '/resource/item/removeResources';
};

export type DeleteResourceResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteResourceResponse = DeleteResourceResponses[keyof DeleteResourceResponses];

export type UpdateResourceTagsData = {
  body: ResourceUpdateTagsRequest;
  path?: never;
  query?: never;
  url: '/resource/item/changeResourceTags';
};

export type UpdateResourceTagsResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateResourceTagsResponse =
  UpdateResourceTagsResponses[keyof UpdateResourceTagsResponses];

export type UpdateResourceActionPermissionData = {
  body: ResourceUpdateActionPermissionRequest;
  path?: never;
  query?: never;
  url: '/resource/item/changeResourceActionPermission';
};

export type UpdateResourceActionPermissionResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateResourceActionPermissionResponse =
  UpdateResourceActionPermissionResponses[keyof UpdateResourceActionPermissionResponses];

export type ChangeResourceLikeStatusData = {
  body: ResourceLikeRequest;
  path?: never;
  query?: never;
  url: '/resource/interaction/toggleLike';
};

export type ChangeResourceLikeStatusResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeResourceLikeStatusResponse =
  ChangeResourceLikeStatusResponses[keyof ChangeResourceLikeStatusResponses];

export type ChangeResourceReadStatusData = {
  body: ResourceReadRequest;
  path?: never;
  query?: never;
  url: '/resource/interaction/read';
};

export type ChangeResourceReadStatusResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeResourceReadStatusResponse =
  ChangeResourceReadStatusResponses[keyof ChangeResourceReadStatusResponses];

export type ChangeResourceScoreData = {
  body: ResourceRateRequest;
  path?: never;
  query?: never;
  url: '/resource/interaction/rate';
};

export type ChangeResourceScoreResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeResourceScoreResponse =
  ChangeResourceScoreResponses[keyof ChangeResourceScoreResponses];

export type UpsertConfigData = {
  body: GroupResConfigUpdateRequest;
  path?: never;
  query?: never;
  url: '/resource/groupConfig/changeConfig';
};

export type UpsertConfigResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpsertConfigResponse = UpsertConfigResponses[keyof UpsertConfigResponses];

export type UpdateCollectionInfoData = {
  body: FavoriteCollectionInfoUpdateRequest;
  path?: never;
  query?: never;
  url: '/resource/favorite/updateCollectionInfo';
};

export type UpdateCollectionInfoResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateCollectionInfoResponse =
  UpdateCollectionInfoResponses[keyof UpdateCollectionInfoResponses];

export type DeleteCollectionData = {
  body: FavoriteCollectionDeleteRequest;
  path?: never;
  query?: never;
  url: '/resource/favorite/deleteCollection';
};

export type DeleteCollectionResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteCollectionResponse = DeleteCollectionResponses[keyof DeleteCollectionResponses];

export type CreateCollectionData = {
  body: FavoriteCollectionCreateRequest;
  path?: never;
  query?: never;
  url: '/resource/favorite/createCollection';
};

export type CreateCollectionResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateCollectionResponse = CreateCollectionResponses[keyof CreateCollectionResponses];

export type ChangeResourceFavoriteStatusData = {
  body: ResourceFavoriteRequest;
  path?: never;
  query?: never;
  url: '/resource/favorite/changeResourceFavoriteStatus';
};

export type ChangeResourceFavoriteStatusResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeResourceFavoriteStatusResponse =
  ChangeResourceFavoriteStatusResponses[keyof ChangeResourceFavoriteStatusResponses];

export type ToggleLikeData = {
  body: CommentLikeRequest;
  path?: never;
  query?: never;
  url: '/resource/comment/toggleLike';
};

export type ToggleLikeResponses = {
  /**
   * OK
   */
  200: RBoolean;
};

export type ToggleLikeResponse = ToggleLikeResponses[keyof ToggleLikeResponses];

export type DeleteCommentItemData = {
  body: CommentDeleteRequest;
  path?: never;
  query?: never;
  url: '/resource/comment/deleteCommentItem';
};

export type DeleteCommentItemResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteCommentItemResponse =
  DeleteCommentItemResponses[keyof DeleteCommentItemResponses];

export type CreateReplyData = {
  body: CommentReplyCreateRequest;
  path?: never;
  query?: never;
  url: '/resource/comment/createReply';
};

export type CreateReplyResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateReplyResponse = CreateReplyResponses[keyof CreateReplyResponses];

export type CreateCommentData = {
  body: CommentCreateRequest;
  path?: never;
  query?: never;
  url: '/resource/comment/createComment';
};

export type CreateCommentResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateCommentResponse = CreateCommentResponses[keyof CreateCommentResponses];

export type AuditSaleData = {
  body: MarketSaleAuditRequest;
  path?: never;
  query?: never;
  url: '/admin/market/auditSale';
};

export type AuditSaleResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type AuditSaleResponse = AuditSaleResponses[keyof AuditSaleResponses];

export type GetTagTreeData = {
  body?: never;
  path?: never;
  query?: {
    groupId?: string;
  };
  url: '/resource/tag/getTagTree';
};

export type GetTagTreeResponses = {
  /**
   * OK
   */
  200: RListTagTreeResponse;
};

export type GetTagTreeResponse = GetTagTreeResponses[keyof GetTagTreeResponses];

export type SearchResourcesData = {
  body?: never;
  path?: never;
  query: {
    keyword?: string;
    scope: SchemaEnum;
    page?: number;
    size?: number;
  };
  url: '/resource/search/globalSearchResources';
};

export type SearchResourcesResponses = {
  /**
   * OK
   */
  200: RPageRSearchHitItemResponse;
};

export type SearchResourcesResponse = SearchResourcesResponses[keyof SearchResourcesResponses];

export type ListOrdersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
  };
  url: '/resource/market/listOrders';
};

export type ListOrdersResponses = {
  /**
   * OK
   */
  200: RPageRMarketOrderResponse;
};

export type ListOrdersResponse = ListOrdersResponses[keyof ListOrdersResponses];

export type ListResourcesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * 小组ID。查个人资源时必须留空
     */
    groupId?: string;
    /**
     * 标签ID列表，为空时列出全部资源。配合 groupId 决定查个人的标签还是小组的标签。
     */
    tagIds?: Array<string>;
    /**
     * 多标签组合查询时的逻辑关系(AND/OR)
     */
    tagQueryLogicMode?: SchemaEnum2;
    resourceType?: string;
    page?: number;
    size?: number;
    /**
     * 排序字段枚举
     */
    sortBy?: SchemaEnum3;
    sortDir?: SchemaEnum4;
  };
  url: '/resource/item/listResources';
};

export type ListResourcesResponses = {
  /**
   * OK
   */
  200: RPageRResourceItemResponse;
};

export type ListResourcesResponse = ListResourcesResponses[keyof ListResourcesResponses];

export type GetResourceUserInteractionRecordData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
  };
  url: '/resource/interaction/getResourceUserInteractionRecord';
};

export type GetResourceUserInteractionRecordResponses = {
  /**
   * OK
   */
  200: RResourceUserInteractionRecordResponse;
};

export type GetResourceUserInteractionRecordResponse =
  GetResourceUserInteractionRecordResponses[keyof GetResourceUserInteractionRecordResponses];

export type GetConfigData = {
  body?: never;
  path?: never;
  query: {
    groupId: string;
  };
  url: '/resource/groupConfig/getConfig';
};

export type GetConfigResponses = {
  /**
   * OK
   */
  200: RGroupResConfigResponse;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type ListFavoritedResourcesData = {
  body?: never;
  path?: never;
  query?: {
    collectionId?: string;
    page?: number;
    size?: number;
  };
  url: '/resource/favorite/listFavoritedResources';
};

export type ListFavoritedResourcesResponses = {
  /**
   * OK
   */
  200: RPageRFavoriteItemResponse;
};

export type ListFavoritedResourcesResponse =
  ListFavoritedResourcesResponses[keyof ListFavoritedResourcesResponses];

export type ListCollectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/resource/favorite/listCollections';
};

export type ListCollectionsResponses = {
  /**
   * OK
   */
  200: RListFavoriteCollectionResponse;
};

export type ListCollectionsResponse = ListCollectionsResponses[keyof ListCollectionsResponses];

export type GetResourceFavoriteStatusData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
  };
  url: '/resource/favorite/getResourceFavoriteStatus';
};

export type GetResourceFavoriteStatusResponses = {
  /**
   * OK
   */
  200: RResourceFavoriteStatusResponse;
};

export type GetResourceFavoriteStatusResponse =
  GetResourceFavoriteStatusResponses[keyof GetResourceFavoriteStatusResponses];

export type ListRepliesData = {
  body?: never;
  path?: never;
  query: {
    rootCommentId: string;
    size?: number;
    page?: number;
  };
  url: '/resource/comment/listReplies';
};

export type ListRepliesResponses = {
  /**
   * OK
   */
  200: RPageRResourceCommentItemResponse;
};

export type ListRepliesResponse = ListRepliesResponses[keyof ListRepliesResponses];

export type ListCommentsData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    sortBy: SchemaEnum5;
    size?: number;
    page?: number;
  };
  url: '/resource/comment/listComments';
};

export type ListCommentsResponses = {
  /**
   * OK
   */
  200: RPageRResourceCommentItemResponse;
};

export type ListCommentsResponse = ListCommentsResponses[keyof ListCommentsResponses];
