// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://172.28.0.28:19905' | (string & {});
};

export type TagDeleteRequest = {
  groupId?: string;
  targetTagId: string;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type TagMoveRequest = {
  groupId?: string;
  targetTagId: string;
  newParentId?: string;
};

export type TagUpdateRequest = {
  groupId?: string;
  tagName?: string;
  tagDesc?: string;
  tagIcon?: string;
  tagColor?: string;
  tagCreator?: string;
  isPath?: boolean;
  taggedResourceAclGrantScope?: TaggedResourceAclGrantScopeEnum;
  taggedResourceAclGrantSpecifiedUsers?: Array<string>;
  taggedResourceGrantedActionsMask?: number;
  tagMountPermissionScope?: TaggedResourceAclGrantScopeEnum;
  tagMountSpecifiedUsers?: Array<string>;
  targetTagId: string;
  grantedActions?: Array<ItemsEnum>;
};

export type TagCreateRequest = {
  groupId?: string;
  parentId?: string;
  tagName: string;
  tagDesc?: string;
  taggedResourceAclGrantScope?: TaggedResourceAclGrantScopeEnum;
  taggedResourceAclGrantSpecifiedUsers?: Array<string>;
  grantedActions?: Array<ItemsEnum>;
  tagMountPermissionScope?: TaggedResourceAclGrantScopeEnum;
  tagMountSpecifiedUsers?: Array<string>;
};

export type RString = {
  code?: number;
  key?: string;
  msg?: string;
  data?: string;
};

export type ResourceRenameRequest = {
  resourceId: string;
  newName: string;
};

export type ResourceUpdateTagsRequest = {
  resourceId: string;
  groupId?: string;
  tagIds: Array<string>;
};

export type ResourceUpdateActionPermissionRequest = {
  resourceId: string;
  overrideGrantedActions?: Array<ItemsEnum>;
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
};

export type ResourceLikeRequest = {
  resourceId: string;
};

export type ResourceReadRequest = {
  resourceId: string;
};

export type ResourceRateRequest = {
  resourceId: string;
  score: number;
};

export type GroupResConfigUpdateRequest = {
  groupId: string;
  fileOrgLogic: FileOrgLogicEnum;
  defaultMemberActions?: Array<ItemsEnum>;
};

export type ResourceInteractionInfoBase = {
  readCount?: number;
  likeCount?: number;
  scoreCount?: number;
  scoreTotal?: number;
};

export type ResourceItemResponse = {
  resourceName?: string;
  resourceType?: ResourceTypeEnum;
  ownerId?: string;
  preview?: string;
  size?: number;
  resourceId?: string;
  ownerInfo?: UserDisplayBase;
  resourceInteractionInfo?: ResourceInteractionInfoBase;
  currentTags?: {
    [key: string]: string;
  };
  currentActions?: Array<ItemsEnum>;
  overrideGrantedActions?: Array<ItemsEnum>;
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
};

export type UserDisplayBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: IdentityTypeEnum;
};

export type RListTagTreeResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: Array<TagTreeResponse>;
};

export type TagTreeResponse = {
  groupId?: string;
  tagName?: string;
  tagDesc?: string;
  tagIcon?: string;
  tagColor?: string;
  tagCreator?: string;
  isPath?: boolean;
  taggedResourceAclGrantScope?: TaggedResourceAclGrantScopeEnum;
  taggedResourceAclGrantSpecifiedUsers?: Array<string>;
  taggedResourceGrantedActionsMask?: number;
  tagMountPermissionScope?: TaggedResourceAclGrantScopeEnum;
  tagMountSpecifiedUsers?: Array<string>;
  tagId?: string;
  parentId?: string;
  grantedActions?: Array<ItemsEnum>;
};

export type PageRSearchHitItemResponse = {
  list?: Array<SearchHitItemResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRSearchHitItemResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRSearchHitItemResponse;
};

export type SearchHitItemResponse = {
  resourceId?: string;
  resourceType?: ResourceTypeEnum;
  resourceName?: string;
  highlightContent?: string;
  updateTime?: string;
};

export type PageRResourceItemResponse = {
  list?: Array<ResourceItemResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRResourceItemResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRResourceItemResponse;
};

export type RResourceUserInteractionRecordResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: ResourceUserInteractionRecordResponse;
};

export type ResourceUserInteractionRecordResponse = {
  read?: boolean;
  liked?: boolean;
  score?: number;
  resourceId?: string;
};

export type GroupResConfigResponse = {
  groupId?: string;
  fileOrgLogic?: FileOrgLogicEnum;
  defaultMemberActions?: Array<ItemsEnum>;
};

export type RGroupResConfigResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: GroupResConfigResponse;
};

export const SchemaEnum = {
  ALL: 'ALL',
  DOCUMENT: 'DOCUMENT',
  NOTE: 'NOTE',
} as const;

export type SchemaEnum = (typeof SchemaEnum)[keyof typeof SchemaEnum];

export const SchemaEnum2 = { AND: 'AND', OR: 'OR' } as const;

export type SchemaEnum2 = (typeof SchemaEnum2)[keyof typeof SchemaEnum2];

export const SchemaEnum3 = {
  UPDATE_TIME: 'UPDATE_TIME',
  CREATE_TIME: 'CREATE_TIME',
  NAME: 'NAME',
  SIZE: 'SIZE',
} as const;

export type SchemaEnum3 = (typeof SchemaEnum3)[keyof typeof SchemaEnum3];

export const SchemaEnum4 = { ASC: 'ASC', DESC: 'DESC' } as const;

export type SchemaEnum4 = (typeof SchemaEnum4)[keyof typeof SchemaEnum4];

export const TaggedResourceAclGrantScopeEnum = {
  ALL: 'ALL',
  ONLY_ADMIN: 'ONLY_ADMIN',
  WHITELIST: 'WHITELIST',
  BLACKLIST: 'BLACKLIST',
} as const;

export type TaggedResourceAclGrantScopeEnum =
  (typeof TaggedResourceAclGrantScopeEnum)[keyof typeof TaggedResourceAclGrantScopeEnum];

export const ItemsEnum = {
  DISCOVER: 'DISCOVER',
  VIEW: 'VIEW',
  EDIT: 'EDIT',
  DOWNLOAD_WATERMARK: 'DOWNLOAD_WATERMARK',
  DOWNLOAD_ORIGINAL: 'DOWNLOAD_ORIGINAL',
} as const;

export type ItemsEnum = (typeof ItemsEnum)[keyof typeof ItemsEnum];

export const FileOrgLogicEnum = { FOLDER: 'FOLDER', TAG: 'TAG' } as const;

export type FileOrgLogicEnum = (typeof FileOrgLogicEnum)[keyof typeof FileOrgLogicEnum];

export const ResourceTypeEnum = {
  NOTE: 'NOTE',
  PDF: 'PDF',
  DOC: 'DOC',
  DOCX: 'DOCX',
  PPT: 'PPT',
  PPTX: 'PPTX',
  XLS: 'XLS',
  XLSX: 'XLSX',
  SKILL: 'SKILL',
  AGENT: 'AGENT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ResourceTypeEnum = (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];

export const IdentityTypeEnum = {
  1: '1',
  2: '2',
  3: '3',
} as const;

export type IdentityTypeEnum = (typeof IdentityTypeEnum)[keyof typeof IdentityTypeEnum];

export type DeleteTagData = {
  body: TagDeleteRequest;
  path?: never;
  query?: never;
  url: '/resource/tag/removeTag';
};

export type DeleteTagResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type MoveTagData = {
  body: TagMoveRequest;
  path?: never;
  query?: never;
  url: '/resource/tag/moveTag';
};

export type MoveTagResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type MoveTagResponse = MoveTagResponses[keyof MoveTagResponses];

export type UpdateTagData = {
  body: TagUpdateRequest;
  path?: never;
  query?: never;
  url: '/resource/tag/changeTag';
};

export type UpdateTagResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateTagResponse = UpdateTagResponses[keyof UpdateTagResponses];

export type CreateTagData = {
  body: TagCreateRequest;
  path?: never;
  query?: never;
  url: '/resource/tag/addTag';
};

export type CreateTagResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type RenameResourceData = {
  body: ResourceRenameRequest;
  path?: never;
  query?: never;
  url: '/resource/item/renameResource';
};

export type RenameResourceResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type RenameResourceResponse = RenameResourceResponses[keyof RenameResourceResponses];

export type DeleteResourceData = {
  body?: never;
  path?: never;
  query: {
    resourceIds: Array<string>;
  };
  url: '/resource/item/removeResources';
};

export type DeleteResourceResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteResourceResponse = DeleteResourceResponses[keyof DeleteResourceResponses];

export type UpdateResourceTagsData = {
  body: ResourceUpdateTagsRequest;
  path?: never;
  query?: never;
  url: '/resource/item/changeResourceTags';
};

export type UpdateResourceTagsResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateResourceTagsResponse =
  UpdateResourceTagsResponses[keyof UpdateResourceTagsResponses];

export type UpdateResourceActionPermissionData = {
  body: ResourceUpdateActionPermissionRequest;
  path?: never;
  query?: never;
  url: '/resource/item/changeResourceActionPermission';
};

export type UpdateResourceActionPermissionResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateResourceActionPermissionResponse =
  UpdateResourceActionPermissionResponses[keyof UpdateResourceActionPermissionResponses];

export type ChangeResourceLikeStatusData = {
  body: ResourceLikeRequest;
  path?: never;
  query?: never;
  url: '/resource/interaction/toggleLike';
};

export type ChangeResourceLikeStatusResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeResourceLikeStatusResponse =
  ChangeResourceLikeStatusResponses[keyof ChangeResourceLikeStatusResponses];

export type ChangeResourceReadStatusData = {
  body: ResourceReadRequest;
  path?: never;
  query?: never;
  url: '/resource/interaction/read';
};

export type ChangeResourceReadStatusResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeResourceReadStatusResponse =
  ChangeResourceReadStatusResponses[keyof ChangeResourceReadStatusResponses];

export type ChangeResourceScoreData = {
  body: ResourceRateRequest;
  path?: never;
  query?: never;
  url: '/resource/interaction/rate';
};

export type ChangeResourceScoreResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeResourceScoreResponse =
  ChangeResourceScoreResponses[keyof ChangeResourceScoreResponses];

export type UpsertConfigData = {
  body: GroupResConfigUpdateRequest;
  path?: never;
  query?: never;
  url: '/resource/groupConfig/changeConfig';
};

export type UpsertConfigResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpsertConfigResponse = UpsertConfigResponses[keyof UpsertConfigResponses];

export type GetTagTreeData = {
  body?: never;
  path?: never;
  query?: {
    groupId?: string;
  };
  url: '/resource/tag/getTagTree';
};

export type GetTagTreeResponses = {
  /**
   * OK
   */
  200: RListTagTreeResponse;
};

export type GetTagTreeResponse = GetTagTreeResponses[keyof GetTagTreeResponses];

export type SearchResourcesData = {
  body?: never;
  path?: never;
  query: {
    keyword?: string;
    scope: SchemaEnum;
    page?: number;
    size?: number;
  };
  url: '/resource/search/globalSearchResources';
};

export type SearchResourcesResponses = {
  /**
   * OK
   */
  200: RPageRSearchHitItemResponse;
};

export type SearchResourcesResponse = SearchResourcesResponses[keyof SearchResourcesResponses];

export type ListResourcesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * 小组ID。查个人资源时必须留空
     */
    groupId?: string;
    /**
     * 标签ID列表，为空时列出全部资源。配合 groupId 决定查个人的标签还是小组的标签。
     */
    tagIds?: Array<string>;
    /**
     * 多标签组合查询时的逻辑关系(AND/OR)
     */
    tagQueryLogicMode?: SchemaEnum2;
    resourceType?: string;
    page?: number;
    size?: number;
    /**
     * 排序字段枚举
     */
    sortBy?: SchemaEnum3;
    sortDir?: SchemaEnum4;
  };
  url: '/resource/item/listResources';
};

export type ListResourcesResponses = {
  /**
   * OK
   */
  200: RPageRResourceItemResponse;
};

export type ListResourcesResponse = ListResourcesResponses[keyof ListResourcesResponses];

export type GetResourceUserInteractionRecordData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
  };
  url: '/resource/interaction/getResourceUserInteractionRecord';
};

export type GetResourceUserInteractionRecordResponses = {
  /**
   * OK
   */
  200: RResourceUserInteractionRecordResponse;
};

export type GetResourceUserInteractionRecordResponse =
  GetResourceUserInteractionRecordResponses[keyof GetResourceUserInteractionRecordResponses];

export type GetConfigData = {
  body?: never;
  path?: never;
  query: {
    groupId: string;
  };
  url: '/resource/groupConfig/getConfig';
};

export type GetConfigResponses = {
  /**
   * OK
   */
  200: RGroupResConfigResponse;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];
