// This file is auto-generated by scripts/sync-openapi.mjs

export * as aiAssetApi from './ai-asset';
export * as documentApi from './document';
export * as fileStorageApi from './file-storage';
export * as fudanExtensionApi from './fudan-extension';
export * as noteApi from './note';
export * as resourceApi from './resource';
export * as systemApi from './system';
export * as userApi from './user';
