// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/docs/proxy/user` | (string & {});
};

export type UserProfileUpdateRequest = {
  sex?: SexEnum;
  university?: string;
  college?: string;
  major?: string;
  className?: string;
  enrollmentYear?: number;
  degreeLevel?: DegreeLevelEnum;
  academicTitle?: string;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type UserInfoUpdateRequest = {
  nickname?: string;
  avatar?: string;
  realName?: string;
};

export type WalletTransferTokenRequest = {
  groupId: number;
  tokenCount: number;
  tokenTransferType?: TokenTransferTypeEnum;
};

export type WalletRedeemVoucherRequest = {
  voucherCode: string;
};

export type GroupDeleteRequest = {
  groupId: number;
};

export type GroupMemberQuitRequest = {
  groupId: number;
};

export type GroupMemberKickRequest = {
  groupId: number;
  targetUserIds: Array<number>;
};

export type GroupMemberTokenLimitUpdateRequest = {
  groupId: number;
  targetUserIds: Array<number>;
  newTokenLimit: number;
};

export type GroupMemberRoleUpdateRequest = {
  groupId: number;
  targetUserIds: Array<number>;
  role: RoleEnum;
};

export type GroupMemberJoinRequest = {
  inviteCode: string;
};

export type GroupUpdateRequest = {
  groupName?: string;
  groupDesc?: string;
  groupCoverUrl?: string;
  groupType?: SchemaEnum5;
  groupId: number;
};

export type GroupCreateRequest = {
  groupName: string;
  groupType: SchemaEnum5;
  groupDesc: string;
  groupCoverUrl?: string;
};

export type RLong = {
  code?: number;
  key?: string;
  msg?: string;
  data?: number;
};

export type AuthPwdResetVerifyRequest = {
  username: string;
  code?: string;
  uuid?: string;
};

export type AuthPwdResetRequest = {
  token: string;
  newPassword: string;
};

export type AuthRegisterRequest = {
  username: string;
  password: string;
};

export type RString = {
  code?: number;
  key?: string;
  msg?: string;
  data?: string;
};

export type AuthLoginRequest = {
  account: string;
  password: string;
  code?: string;
  uuid?: string;
};

export type WalletChangeCoinBalanceRequest = {
  userId: number;
  changedCoin: number;
  walletTransactionType: SchemaEnum;
  meta?: string;
};

export type AuthPwdAdminResetRequest = {
  userId: number;
  newPassword?: string;
};

export type UserProfileAdminUpdateRequest = {
  sex?: SexEnum;
  university?: string;
  college?: string;
  major?: string;
  className?: string;
  enrollmentYear?: number;
  degreeLevel?: DegreeLevelEnum;
  academicTitle?: string;
  userId?: number;
};

export type UserInfoAdminUpdateRequest = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: SchemaEnum5;
  username?: string;
  campusNo?: string;
  email?: string;
  mobile?: string;
  verificationMode?: VerificationModeEnum;
  status?: SchemaEnum4;
  userId?: number;
};

export type PageRWalletTransactionRecordResponse = {
  list?: Array<WalletTransactionRecordResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRWalletTransactionRecordResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRWalletTransactionRecordResponse;
};

export type UserDisplayBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: SchemaEnum5;
};

export type WalletTransactionRecordResponse = {
  traceId?: string;
  operatorId?: number;
  count?: number;
  walletTransactionType?: SchemaEnum;
  walletBusinessType?: SchemaEnum2;
  meta?: string;
  operatorDisplay?: UserDisplayBase;
  createTime?: string;
};

export type RWalletDetailResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: WalletDetailResponse;
};

export type WalletDetailResponse = {
  tokenUsed?: number;
  tokenBalance?: number;
  coinBalance?: number;
};

export type RVerificationResultDto = {
  code?: number;
  key?: string;
  msg?: string;
  data?: VerificationResultDto;
};

export type VerificationResultDto = {
  completed?: boolean;
  requireAction?: boolean;
  actionPayload?: string;
  message?: string;
};

export type RuserDetailInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: UserDetailInfoResponse;
};

export type UserDetailInfoResponse = {
  userId?: number;
  userInfo?: UserInfoBase;
  userProfile?: UserProfileBase;
  readonlyFields?: Array<string>;
};

export type UserInfoBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: SchemaEnum5;
  username?: string;
  campusNo?: string;
  email?: string;
  mobile?: string;
  verificationMode?: VerificationModeEnum;
  status?: SchemaEnum4;
};

export type UserProfileBase = {
  sex?: SexEnum;
  university?: string;
  college?: string;
  major?: string;
  className?: string;
  enrollmentYear?: number;
  degreeLevel?: DegreeLevelEnum;
  academicTitle?: string;
};

export type GroupDisplayBase = {
  groupName?: string;
  groupDesc?: string;
  groupCoverUrl?: string;
  groupType?: SchemaEnum5;
};

export type GroupMemberDetailResponse = {
  role?: RoleEnum;
  joinTime?: string;
  tokenLimit?: number;
  tokenUsed?: number;
  groupId?: number;
  memberId?: number;
  memberInfo?: UserDisplayBase;
};

export type PageRGroupMemberDetailResponse = {
  list?: Array<GroupMemberDetailResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRGroupMemberDetailResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRGroupMemberDetailResponse;
};

export type RGroupRoleType = {
  code?: number;
  key?: string;
  msg?: string;
  data?: RoleEnum;
};

export type RGroupMemberDetailResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: GroupMemberDetailResponse;
};

export type GroupMemberTokenDetailResponse = {
  groupDisplayBase?: GroupDisplayBase;
  tokenUsed?: number;
  tokenLimit?: number;
};

export type PageRGroupMemberTokenDetailResponse = {
  list?: Array<GroupMemberTokenDetailResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRGroupMemberTokenDetailResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRGroupMemberTokenDetailResponse;
};

export type GroupItemInfoResponse = {
  groupName?: string;
  groupDesc?: string;
  groupCoverUrl?: string;
  groupType?: SchemaEnum5;
  groupId?: number;
  ownerId?: number;
  ownerInfo?: UserDisplayBase;
  memberCount?: number;
  createTime?: string;
};

export type PageRGroupItemInfoResponse = {
  list?: Array<GroupItemInfoResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRGroupItemInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRGroupItemInfoResponse;
};

export type GroupDetailInfoResponse = {
  groupName?: string;
  groupDesc?: string;
  groupCoverUrl?: string;
  groupType?: SchemaEnum5;
  groupId?: number;
  ownerId?: number;
  ownerInfo?: UserDisplayBase;
  memberCount?: number;
  createTime?: string;
  inviteCode?: string;
  tokenUsed?: number;
  tokenBalance?: number;
};

export type RGroupDetailInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: GroupDetailInfoResponse;
};

export type RGroupItemInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: GroupItemInfoResponse;
};

export type PageRuserEntity = {
  list?: Array<UserEntity>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRuserEntity = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRuserEntity;
};

export type UserEntity = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: SchemaEnum5;
  username?: string;
  campusNo?: string;
  email?: string;
  mobile?: string;
  verificationMode?: VerificationModeEnum;
  status?: SchemaEnum4;
  userId?: number;
  password?: string;
  delFlag?: number;
  createTime?: string;
  updateTime?: string;
};

export type RuserProfileEntity = {
  code?: number;
  key?: string;
  msg?: string;
  data?: UserProfileEntity;
};

export type UserProfileEntity = {
  sex?: SexEnum;
  university?: string;
  college?: string;
  major?: string;
  className?: string;
  enrollmentYear?: number;
  degreeLevel?: DegreeLevelEnum;
  academicTitle?: string;
  userId?: number;
  createTime?: string;
  updateTime?: string;
};

export const SchemaEnum = {
  REFILL: 'REFILL',
  SPEND: 'SPEND',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  INCOME: 'INCOME',
  EXCHANGE: 'EXCHANGE',
  REVERSE: 'REVERSE',
} as const;

export type SchemaEnum = (typeof SchemaEnum)[keyof typeof SchemaEnum];

export const SchemaEnum2 = { TOKEN: 'TOKEN', COIN: 'COIN' } as const;

export type SchemaEnum2 = (typeof SchemaEnum2)[keyof typeof SchemaEnum2];

export const SchemaEnum3 = { JOINED: 'JOINED', MANAGED: 'MANAGED' } as const;

export type SchemaEnum3 = (typeof SchemaEnum3)[keyof typeof SchemaEnum3];

export const SchemaEnum4 = {
  NORMAL: 'NORMAL',
  UNIDENTIFIED: 'UNIDENTIFIED',
  BANNED: 'BANNED',
} as const;

export type SchemaEnum4 = (typeof SchemaEnum4)[keyof typeof SchemaEnum4];

export const SchemaEnum5 = {
  1: '1',
  2: '2',
  3: '3',
} as const;

export type SchemaEnum5 = (typeof SchemaEnum5)[keyof typeof SchemaEnum5];

export const SexEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export type SexEnum = (typeof SexEnum)[keyof typeof SexEnum];

export const DegreeLevelEnum = {
  UNKNOWN: 'UNKNOWN',
  UNDERGRADUATE: 'UNDERGRADUATE',
  MASTER: 'MASTER',
  DOCTOR: 'DOCTOR',
} as const;

export type DegreeLevelEnum = (typeof DegreeLevelEnum)[keyof typeof DegreeLevelEnum];

export const TokenTransferTypeEnum = {
  GROUP_INFLOW: 'GROUP_INFLOW',
  USER_INFLOW: 'USER_INFLOW',
} as const;

export type TokenTransferTypeEnum =
  (typeof TokenTransferTypeEnum)[keyof typeof TokenTransferTypeEnum];

export const RoleEnum = {
  0: '0',
  1: '1',
  2: '2',
  '-1': '-1',
} as const;

export type RoleEnum = (typeof RoleEnum)[keyof typeof RoleEnum];

export const VerificationModeEnum = { EDU_EMAIL: 'EDU_EMAIL', FDU_UIS_SYS: 'FDU_UIS_SYS' } as const;

export type VerificationModeEnum = (typeof VerificationModeEnum)[keyof typeof VerificationModeEnum];

export type UpdateUserProfileData = {
  body: UserProfileUpdateRequest;
  path?: never;
  query?: never;
  url: '/user/changeUserProfile';
};

export type UpdateUserProfileResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateUserProfileResponse =
  UpdateUserProfileResponses[keyof UpdateUserProfileResponses];

export type UpdateUserInfoData = {
  body: UserInfoUpdateRequest;
  path?: never;
  query?: never;
  url: '/user/changeUserInfo';
};

export type UpdateUserInfoResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateUserInfoResponse = UpdateUserInfoResponses[keyof UpdateUserInfoResponses];

export type TransferTokenBetweenGroupAndUserData = {
  body: WalletTransferTokenRequest;
  path?: never;
  query?: never;
  url: '/user/wallet/transferTokenBetweenGroupAndUser';
};

export type TransferTokenBetweenGroupAndUserResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type TransferTokenBetweenGroupAndUserResponse =
  TransferTokenBetweenGroupAndUserResponses[keyof TransferTokenBetweenGroupAndUserResponses];

export type RedeemVoucherData = {
  body: WalletRedeemVoucherRequest;
  path?: never;
  query?: never;
  url: '/user/wallet/redeemVoucher';
};

export type RedeemVoucherResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type RedeemVoucherResponse = RedeemVoucherResponses[keyof RedeemVoucherResponses];

export type InitiateFudanUisVerifyData = {
  body?: never;
  path?: never;
  query: {
    uisAccount: string;
    uisPassword: string;
  };
  url: '/user/verify/initiateFudanUISVerify';
};

export type InitiateFudanUisVerifyResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type InitiateFudanUisVerifyResponse =
  InitiateFudanUisVerifyResponses[keyof InitiateFudanUisVerifyResponses];

export type InitiateEmailVerifyData = {
  body?: never;
  path?: never;
  query: {
    email: string;
  };
  url: '/user/verify/initiateEmailVerify';
};

export type InitiateEmailVerifyResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type InitiateEmailVerifyResponse =
  InitiateEmailVerifyResponses[keyof InitiateEmailVerifyResponses];

export type DeleteGroupData = {
  body: GroupDeleteRequest;
  path?: never;
  query?: never;
  url: '/group/removeGroup';
};

export type DeleteGroupResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type QuitGroupData = {
  body: GroupMemberQuitRequest;
  path?: never;
  query?: never;
  url: '/group/member/quit';
};

export type QuitGroupResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type QuitGroupResponse = QuitGroupResponses[keyof QuitGroupResponses];

export type KickGroupMembersData = {
  body: GroupMemberKickRequest;
  path?: never;
  query?: never;
  url: '/group/member/kick';
};

export type KickGroupMembersResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type KickGroupMembersResponse = KickGroupMembersResponses[keyof KickGroupMembersResponses];

export type ChangeTokenLimitData = {
  body: GroupMemberTokenLimitUpdateRequest;
  path?: never;
  query?: never;
  url: '/group/member/changeTokenLimit';
};

export type ChangeTokenLimitResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeTokenLimitResponse = ChangeTokenLimitResponses[keyof ChangeTokenLimitResponses];

export type ChangeRoleData = {
  body: GroupMemberRoleUpdateRequest;
  path?: never;
  query?: never;
  url: '/group/member/changeRole';
};

export type ChangeRoleResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeRoleResponse = ChangeRoleResponses[keyof ChangeRoleResponses];

export type JoinGroupData = {
  body: GroupMemberJoinRequest;
  path?: never;
  query?: never;
  url: '/group/joinGroup';
};

export type JoinGroupResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type JoinGroupResponse = JoinGroupResponses[keyof JoinGroupResponses];

export type UpdateGroupData = {
  body: GroupUpdateRequest;
  path?: never;
  query?: never;
  url: '/group/changeGroup';
};

export type UpdateGroupResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateGroupResponse = UpdateGroupResponses[keyof UpdateGroupResponses];

export type CreateGroupData = {
  body: GroupCreateRequest;
  path?: never;
  query?: never;
  url: '/group/addGroup';
};

export type CreateGroupResponses = {
  /**
   * OK
   */
  200: RLong;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type SendResetMailData = {
  body: AuthPwdResetVerifyRequest;
  path?: never;
  query?: never;
  url: '/auth/sendResetMail';
};

export type SendResetMailResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type SendResetMailResponse = SendResetMailResponses[keyof SendResetMailResponses];

export type ResetPasswordData = {
  body: AuthPwdResetRequest;
  path?: never;
  query?: never;
  url: '/auth/resetPassword';
};

export type ResetPasswordResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type RegisterData = {
  body: AuthRegisterRequest;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type RegisterResponses = {
  /**
   * OK
   */
  200: RString;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type LogoutResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
  body: AuthLoginRequest;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type LoginResponses = {
  /**
   * OK
   */
  200: RString;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type ChangeBalanceData = {
  body: WalletChangeCoinBalanceRequest;
  path?: never;
  query?: never;
  url: '/admin/user/wallet/changeBalance';
};

export type ChangeBalanceResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ChangeBalanceResponse = ChangeBalanceResponses[keyof ChangeBalanceResponses];

export type ResetPassword1Data = {
  body: AuthPwdAdminResetRequest;
  path?: never;
  query?: never;
  url: '/admin/user/resetPassword';
};

export type ResetPassword1Responses = {
  /**
   * OK
   */
  200: RVoid;
};

export type ResetPassword1Response = ResetPassword1Responses[keyof ResetPassword1Responses];

export type UpdateUserProfile1Data = {
  body: UserProfileAdminUpdateRequest;
  path?: never;
  query?: never;
  url: '/admin/user/changeUserProfile';
};

export type UpdateUserProfile1Responses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateUserProfile1Response =
  UpdateUserProfile1Responses[keyof UpdateUserProfile1Responses];

export type UpdateUserInfo1Data = {
  body: UserInfoAdminUpdateRequest;
  path?: never;
  query?: never;
  url: '/admin/user/changeUserInfo';
};

export type UpdateUserInfo1Responses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateUserInfo1Response = UpdateUserInfo1Responses[keyof UpdateUserInfo1Responses];

export type ListTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    groupId?: number;
    walletTransactionType?: SchemaEnum;
    walletBusinessType?: SchemaEnum2;
    page?: number;
    size?: number;
  };
  url: '/user/wallet/listTransactions';
};

export type ListTransactionsResponses = {
  /**
   * OK
   */
  200: RPageRWalletTransactionRecordResponse;
};

export type ListTransactionsResponse = ListTransactionsResponses[keyof ListTransactionsResponses];

export type GetUserWalletInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/wallet/getUserWalletInfo';
};

export type GetUserWalletInfoResponses = {
  /**
   * OK
   */
  200: RWalletDetailResponse;
};

export type GetUserWalletInfoResponse =
  GetUserWalletInfoResponses[keyof GetUserWalletInfoResponses];

export type CheckFudanUisVerifyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/verify/checkFudanUISVerify';
};

export type CheckFudanUisVerifyResponses = {
  /**
   * OK
   */
  200: RVerificationResultDto;
};

export type CheckFudanUisVerifyResponse =
  CheckFudanUisVerifyResponses[keyof CheckFudanUisVerifyResponses];

export type CheckEmailVerifyData = {
  body?: never;
  path?: never;
  query: {
    token: string;
  };
  url: '/user/verify/checkEmailVerify';
};

export type CheckEmailVerifyResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type CheckEmailVerifyResponse = CheckEmailVerifyResponses[keyof CheckEmailVerifyResponses];

export type GetUserInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/getUserInfo';
};

export type GetUserInfoResponses = {
  /**
   * OK
   */
  200: RuserDetailInfoResponse;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type ListGroupMembersData = {
  body?: never;
  path?: never;
  query: {
    groupId: number;
    page?: number;
    size?: number;
  };
  url: '/group/member/list';
};

export type ListGroupMembersResponses = {
  /**
   * OK
   */
  200: RPageRGroupMemberDetailResponse;
};

export type ListGroupMembersResponse = ListGroupMembersResponses[keyof ListGroupMembersResponses];

export type GetMyRoleData = {
  body?: never;
  path?: never;
  query: {
    groupId: number;
  };
  url: '/group/member/getMyRole';
};

export type GetMyRoleResponses = {
  /**
   * OK
   */
  200: RGroupRoleType;
};

export type GetMyRoleResponse = GetMyRoleResponses[keyof GetMyRoleResponses];

export type GetMyGroupMemberInfoData = {
  body?: never;
  path?: never;
  query: {
    groupId: number;
  };
  url: '/group/member/getMyGroupMemberInfo';
};

export type GetMyGroupMemberInfoResponses = {
  /**
   * OK
   */
  200: RGroupMemberDetailResponse;
};

export type GetMyGroupMemberInfoResponse =
  GetMyGroupMemberInfoResponses[keyof GetMyGroupMemberInfoResponses];

export type GetAllMyGroupTokenInfoData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
  };
  url: '/group/member/getAllMyGroupTokenInfo';
};

export type GetAllMyGroupTokenInfoResponses = {
  /**
   * OK
   */
  200: RPageRGroupMemberTokenDetailResponse;
};

export type GetAllMyGroupTokenInfoResponse =
  GetAllMyGroupTokenInfoResponses[keyof GetAllMyGroupTokenInfoResponses];

export type ListGroupsData = {
  body?: never;
  path?: never;
  query: {
    groupRoleFilter: SchemaEnum3;
    page?: number;
    size?: number;
  };
  url: '/group/list';
};

export type ListGroupsResponses = {
  /**
   * OK
   */
  200: RPageRGroupItemInfoResponse;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type GetGroupDetailInfoData = {
  body?: never;
  path?: never;
  query: {
    groupId: number;
  };
  url: '/group/getGroupDetailInfo';
};

export type GetGroupDetailInfoResponses = {
  /**
   * OK
   */
  200: RGroupDetailInfoResponse;
};

export type GetGroupDetailInfoResponse =
  GetGroupDetailInfoResponses[keyof GetGroupDetailInfoResponses];

export type GetGroupBaseInfoData = {
  body?: never;
  path?: never;
  query: {
    groupId: number;
  };
  url: '/group/getGroupBaseInfo';
};

export type GetGroupBaseInfoResponses = {
  /**
   * OK
   */
  200: RGroupItemInfoResponse;
};

export type GetGroupBaseInfoResponse = GetGroupBaseInfoResponses[keyof GetGroupBaseInfoResponses];

export type GetUserListData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
    keyword?: string;
    status?: SchemaEnum4;
    identityType?: SchemaEnum5;
  };
  url: '/admin/user/getUserList';
};

export type GetUserListResponses = {
  /**
   * OK
   */
  200: RPageRuserEntity;
};

export type GetUserListResponse = GetUserListResponses[keyof GetUserListResponses];

export type GetUserInfo1Data = {
  body?: never;
  path?: never;
  query: {
    userId: number;
  };
  url: '/admin/user/getUserInfo';
};

export type GetUserInfo1Responses = {
  /**
   * OK
   */
  200: RuserProfileEntity;
};

export type GetUserInfo1Response = GetUserInfo1Responses[keyof GetUserInfo1Responses];
