// This file is auto-generated by @hey-api/openapi-ts

export {
  SchemaEnum,
  type ClientOptions,
  type HandleUploadCallbackData,
  type HandleUploadCallbackResponse,
  type HandleUploadCallbackResponses,
  type RStorageRecordDto,
  type StorageRecordDto,
  type UploadImageProxyData,
  type UploadImageProxyResponse,
  type UploadImageProxyResponses,
} from './types.gen';
