// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/docs/proxy/file-storage` | (string & {});
};

export type RStorageRecordDto = {
  code?: number;
  key?: string;
  msg?: string;
  data?: StorageRecordDto;
};

export type StorageRecordDto = {
  objectKey?: string;
  md5?: string;
  size?: number;
  fileId?: number;
  domain?: string;
};

export const SchemaEnum = {
  PUBLIC_IMAGE_FOR_USER: 'PUBLIC_IMAGE_FOR_USER',
  PUBLIC_IMAGE_FOR_GROUP: 'PUBLIC_IMAGE_FOR_GROUP',
  PRIVATE_IMAGE_FOR_NOTE: 'PRIVATE_IMAGE_FOR_NOTE',
  PRIVATE_DOC: 'PRIVATE_DOC',
  PRIVATE_SKILL_ASSET: 'PRIVATE_SKILL_ASSET',
  PRIVATE_AGENT_ASSET: 'PRIVATE_AGENT_ASSET',
} as const;

export type SchemaEnum = (typeof SchemaEnum)[keyof typeof SchemaEnum];

export type UploadImageProxyData = {
  body?: {
    file: Blob | File;
  };
  path?: never;
  query?: {
    scene?: SchemaEnum;
    bizTag?: string;
  };
  url: '/storage/imageUpload';
};

export type UploadImageProxyResponses = {
  /**
   * OK
   */
  200: RStorageRecordDto;
};

export type UploadImageProxyResponse = UploadImageProxyResponses[keyof UploadImageProxyResponses];

export type HandleUploadCallbackData = {
  body?: string;
  path?: never;
  query?: never;
  url: '/external/storage/callback/upload';
};

export type HandleUploadCallbackResponses = {
  /**
   * OK
   */
  200: string;
};

export type HandleUploadCallbackResponse =
  HandleUploadCallbackResponses[keyof HandleUploadCallbackResponses];
