// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://172.28.0.25:19908' | (string & {});
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type NoteCreateRequest = {
  title: string;
};

export type RString = {
  code?: number;
  key?: string;
  msg?: string;
  data?: string;
};

export type NoteOperationLogResponse = {
  userId?: string;
  operationType?: string;
  contentSummary?: string;
  timestamp?: string;
  mergedCount?: number;
  details?: {
    [key: string]: unknown;
  };
  id?: string;
};

export type PageRNoteOperationLogResponse = {
  list?: Array<NoteOperationLogResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRNoteOperationLogResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRNoteOperationLogResponse;
};

export type NoteVersionListResponse = {
  version?: number;
  type?: TypeEnum;
  label?: string;
  createdAt?: string;
  createdBy?: Array<number>;
  id?: string;
};

export type PageRNoteVersionListResponse = {
  list?: Array<NoteVersionListResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRNoteVersionListResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRNoteVersionListResponse;
};

export type NoteInfoBase = {
  lastUpdatedAt?: string;
  authors?: Array<number>;
};

export type NoteInfoResponse = {
  resourceInfo?: ResourceItemResponse;
  noteInfo?: NoteInfoBase;
  authorsDisplay?: {
    [key: string]: UserDisplayBase;
  };
};

export type RNoteInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: NoteInfoResponse;
};

export type ResourceInteractionInfoBase = {
  readCount?: number;
  likeCount?: number;
  scoreCount?: number;
  scoreTotal?: number;
};

export type ResourceItemResponse = {
  resourceName?: string;
  resourceType?: ResourceTypeEnum;
  ownerId?: string;
  preview?: string;
  size?: number;
  resourceId?: string;
  ownerInfo?: UserDisplayBase;
  resourceInteractionInfo?: ResourceInteractionInfoBase;
  currentTags?: {
    [key: string]: string;
  };
  currentActions?: Array<ItemsEnum>;
  overrideGrantedActions?: Array<ItemsEnum>;
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
};

export type UserDisplayBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: IdentityTypeEnum;
};

export const TypeEnum = { FULL: 'FULL', DELTA: 'DELTA' } as const;

export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];

export const ResourceTypeEnum = {
  NOTE: 'NOTE',
  PDF: 'PDF',
  DOC: 'DOC',
  DOCX: 'DOCX',
  PPT: 'PPT',
  PPTX: 'PPTX',
  XLS: 'XLS',
  XLSX: 'XLSX',
  SKILL: 'SKILL',
  AGENT: 'AGENT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ResourceTypeEnum = (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];

export const ItemsEnum = {
  DISCOVER: 'DISCOVER',
  VIEW: 'VIEW',
  EDIT: 'EDIT',
  DOWNLOAD_WATERMARK: 'DOWNLOAD_WATERMARK',
  DOWNLOAD_ORIGINAL: 'DOWNLOAD_ORIGINAL',
} as const;

export type ItemsEnum = (typeof ItemsEnum)[keyof typeof ItemsEnum];

export const IdentityTypeEnum = {
  1: '1',
  2: '2',
  3: '3',
} as const;

export type IdentityTypeEnum = (typeof IdentityTypeEnum)[keyof typeof IdentityTypeEnum];

export type RevertToVersionData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    version: number;
  };
  url: '/note/revertNote';
};

export type RevertToVersionResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type RevertToVersionResponse = RevertToVersionResponses[keyof RevertToVersionResponses];

export type CreateNoteData = {
  body: NoteCreateRequest;
  path?: never;
  query?: never;
  url: '/note/addNote';
};

export type CreateNoteResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateNoteResponse = CreateNoteResponses[keyof CreateNoteResponses];

export type ListNoteOperationLogsData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    page?: number;
    size?: number;
  };
  url: '/note/log/getNoteOpLogs';
};

export type ListNoteOperationLogsResponses = {
  /**
   * OK
   */
  200: RPageRNoteOperationLogResponse;
};

export type ListNoteOperationLogsResponse =
  ListNoteOperationLogsResponses[keyof ListNoteOperationLogsResponses];

export type ListNoteHistoryVersionsData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    page?: number;
    size?: number;
  };
  url: '/note/listNoteHistoryVersions';
};

export type ListNoteHistoryVersionsResponses = {
  /**
   * OK
   */
  200: RPageRNoteVersionListResponse;
};

export type ListNoteHistoryVersionsResponse =
  ListNoteHistoryVersionsResponses[keyof ListNoteHistoryVersionsResponses];

export type GetNoteInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
  };
  url: '/note/getNoteInfo';
};

export type GetNoteInfoResponses = {
  /**
   * OK
   */
  200: RNoteInfoResponse;
};

export type GetNoteInfoResponse = GetNoteInfoResponses[keyof GetNoteInfoResponses];
