// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/docs/proxy/note` | (string & {});
};

export type NoteSnapshotSaveRequest = {
  resourceId?: string;
  version?: number;
  type?: TypeEnum;
  data?: string;
  plainText?: string;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type NoteForkRequest = {
  resourceId: string;
  forkedResourceVersion?: number;
  forkedResourceName?: string;
};

export type RString = {
  code?: number;
  key?: string;
  msg?: string;
  data?: string;
};

export type NoteCreateRequest = {
  title: string;
  resourceType?: ResourceTypeEnum;
};

export type NoteOperationLogResponse = {
  userId?: string;
  operationType?: string;
  contentSummary?: string;
  timestamp?: string;
  mergedCount?: number;
  details?: {
    [key: string]: unknown;
  };
  id?: string;
};

export type PageRNoteOperationLogResponse = {
  list?: Array<NoteOperationLogResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRNoteOperationLogResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRNoteOperationLogResponse;
};

export type NoteVersionInfoResponse = {
  type?: TypeEnum;
  createdBy?: Array<number>;
  version?: number;
};

export type PageRNoteVersionInfoResponse = {
  list?: Array<NoteVersionInfoResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRNoteVersionInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRNoteVersionInfoResponse;
};

export type MarketSaleInfoResponse = {
  reviewActions?: Array<ItemsEnum>;
  reviewContentPercentage?: number;
  marketSaleTiers?: Array<MarketSaleTierResponse>;
  status?: StatusEnum;
  offerVersion?: number;
  auditMessage?: string;
  auditAt?: string;
};

export type MarketSaleTierResponse = {
  offerId?: string;
  grantedActions?: Array<ItemsEnum>;
  price?: number;
};

export type NoteInfoResponse = {
  resourceInfo?: ResourceItemResponse;
  version?: number;
  authorsDisplay?: {
    [key: string]: UserDisplayBase;
  };
};

export type RNoteInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: NoteInfoResponse;
};

export type ResourceInteractionInfoBase = {
  readCount?: number;
  likeCount?: number;
  scoreCount?: number;
  scoreTotal?: number;
  favoriteCount?: number;
  commentCount?: number;
};

export type ResourceItemResponse = {
  resourceName?: string;
  resourceType?: ResourceTypeEnum;
  ownerId?: string;
  preview?: string;
  size?: number;
  resourceInteractionInfo?: ResourceInteractionInfoBase;
  resourceId?: string;
  ownerInfo?: UserDisplayBase;
  currentTags?: {
    [key: string]: TagInfoBase;
  };
  currentActions?: Array<ItemsEnum>;
  overrideGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
  marketSaleInfos?: {
    [key: string]: MarketSaleInfoResponse;
  };
};

export type TagInfoBase = {
  groupId?: string;
  tagName?: string;
  tagDesc?: string;
  tagIcon?: string;
  tagColor?: string;
  tagCreator?: string;
  isPath?: boolean;
};

export type UserDisplayBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: IdentityTypeEnum;
};

export const TypeEnum = { FULL: 'FULL', DELTA: 'DELTA' } as const;

export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];

export const ResourceTypeEnum = {
  NOTE: 'NOTE',
  DRAWIO: 'DRAWIO',
  PDF: 'PDF',
  DOC: 'DOC',
  DOCX: 'DOCX',
  PPT: 'PPT',
  PPTX: 'PPTX',
  XLS: 'XLS',
  XLSX: 'XLSX',
  SKILL: 'SKILL',
  AGENT: 'AGENT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ResourceTypeEnum = (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];

export const ItemsEnum = {
  DISCOVER: 'DISCOVER',
  VIEW: 'VIEW',
  LOAD: 'LOAD',
  EDIT: 'EDIT',
  INLINE_COMMENT: 'INLINE_COMMENT',
  DOWNLOAD_WATERMARK: 'DOWNLOAD_WATERMARK',
  DOWNLOAD_ORIGINAL: 'DOWNLOAD_ORIGINAL',
  FORK: 'FORK',
  COMMENT: 'COMMENT',
} as const;

export type ItemsEnum = (typeof ItemsEnum)[keyof typeof ItemsEnum];

export const StatusEnum = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
  BANNED: 'BANNED',
  OFF_SHELF: 'OFF_SHELF',
} as const;

export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];

export const IdentityTypeEnum = {
  1: '1',
  2: '2',
  3: '3',
} as const;

export type IdentityTypeEnum = (typeof IdentityTypeEnum)[keyof typeof IdentityTypeEnum];

export type SaveDrawIoSnapshotData = {
  body: NoteSnapshotSaveRequest;
  path?: never;
  query?: never;
  url: '/note/saveDrawIOSnapshot';
};

export type SaveDrawIoSnapshotResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type SaveDrawIoSnapshotResponse =
  SaveDrawIoSnapshotResponses[keyof SaveDrawIoSnapshotResponses];

export type RevertToVersionData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    version: number;
  };
  url: '/note/revertNote';
};

export type RevertToVersionResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type RevertToVersionResponse = RevertToVersionResponses[keyof RevertToVersionResponses];

export type ForkNoteData = {
  body: NoteForkRequest;
  path?: never;
  query?: never;
  url: '/note/forkNote';
};

export type ForkNoteResponses = {
  /**
   * OK
   */
  200: RString;
};

export type ForkNoteResponse = ForkNoteResponses[keyof ForkNoteResponses];

export type CreateNoteData = {
  body: NoteCreateRequest;
  path?: never;
  query?: never;
  url: '/note/addNote';
};

export type CreateNoteResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateNoteResponse = CreateNoteResponses[keyof CreateNoteResponses];

export type ListNoteOperationLogsData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    page?: number;
    size?: number;
  };
  url: '/note/log/getNoteOpLogs';
};

export type ListNoteOperationLogsResponses = {
  /**
   * OK
   */
  200: RPageRNoteOperationLogResponse;
};

export type ListNoteOperationLogsResponse =
  ListNoteOperationLogsResponses[keyof ListNoteOperationLogsResponses];

export type ListNoteVersionsData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    page?: number;
    size?: number;
  };
  url: '/note/listNoteVersions';
};

export type ListNoteVersionsResponses = {
  /**
   * OK
   */
  200: RPageRNoteVersionInfoResponse;
};

export type ListNoteVersionsResponse = ListNoteVersionsResponses[keyof ListNoteVersionsResponses];

export type GetNoteInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    targetVersion?: number;
  };
  url: '/note/getNoteInfo';
};

export type GetNoteInfoResponses = {
  /**
   * OK
   */
  200: RNoteInfoResponse;
};

export type GetNoteInfoResponse = GetNoteInfoResponses[keyof GetNoteInfoResponses];
