// This file is auto-generated by scripts/sync-openapi.mjs

export {
  IdentityTypeEnum,
  ItemsEnum,
  ResourceTypeEnum,
  SkillAssetResourceTypeEnum,
  SourceTypeEnum,
  StatusEnum,
  UploadStatusEnum,
} from '../api/ai-asset/types.gen';

export const enumDescriptionMap = {} as const;
