// This file is auto-generated by scripts/sync-openapi.mjs

export {
  DocumentTypeEnum,
  ForcesavetypeEnum,
  IdentityTypeEnum,
  ItemsEnum,
  MacrosModeEnum,
  ModeEnum,
  PermissionsEnum,
  ResourceTypeEnum,
  ReviewDisplayEnum,
  StatusEnum,
  ToolbarDockedEnum,
  TypeEnum,
  UnitEnum,
} from '../api/document/types.gen';

export const enumDescriptionMap = {} as const;
