// This file is auto-generated by scripts/sync-openapi.mjs

export { FileTypeEnum, IdentityTypeEnum, ItemsEnum, StatusEnum } from '../api/document/types.gen';

export const enumDescriptionMap = {} as const;
