// This file is auto-generated by scripts/sync-openapi.mjs

export * as aiAssetEnums from './ai-asset.gen';
export * as documentEnums from './document.gen';
export * as fileStorageEnums from './file-storage.gen';
export * as fudanExtensionEnums from './fudan-extension.gen';
export * as noteEnums from './note.gen';
export * as resourceEnums from './resource.gen';
export * as systemEnums from './system.gen';
export * as userEnums from './user.gen';
