// This file is auto-generated by scripts/sync-openapi.mjs

export { IdentityTypeEnum, ItemsEnum, ResourceTypeEnum, TypeEnum } from '../api/note/types.gen';

export const enumDescriptionMap = {} as const;
