// This file is auto-generated by scripts/sync-openapi.mjs

export {
  AdditionalPropertiesEnum,
  FileOrgLogicEnum,
  IdentityTypeEnum,
  ItemsEnum,
  ResourceAccessRoleEnum,
  ResourceTypeEnum,
  SchemaEnum,
  TaggedResourceAclGrantScopeEnum,
} from '../api/resource/types.gen';

export const enumDescriptionMap = {} as const;
