// This file is auto-generated by scripts/sync-openapi.mjs

export {
  DegreeLevelEnum,
  RoleEnum,
  SchemaEnum,
  SexEnum,
  TokenTransferTypeEnum,
  VerificationModeEnum,
} from '../api/user/types.gen';

export const enumDescriptionMap = {} as const;
