// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://172.28.0.6:19910' | (string & {});
};

export type SkillVersionPublishRequest = {
  resourceId: string;
  draftVersion: number;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type SkillAssetUploadInitRequest = {
  resourceId: string;
  draftVersion?: number;
  assets: Array<SkillAssetUploadRequest>;
};

export type SkillAssetUploadRequest = {
  name: string;
  path: string;
  skillAssetResourceType: SkillAssetResourceTypeEnum;
  md5?: string;
  expectedSize?: number;
};

export type AssetUploadTicket = {
  assetId?: string;
  path?: string;
  name?: string;
  objectKey?: string;
  putUrl?: string;
  callbackHeader?: string;
  flashUploaded?: boolean;
};

export type RSkillAssetUploadInitResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: SkillAssetUploadInitResponse;
};

export type SkillAssetUploadInitResponse = {
  resourceId?: string;
  version?: number;
  assetUploadTickets?: Array<AssetUploadTicket>;
};

export type RSkillVersionInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: SkillVersionInfoResponse;
};

export type SkillAssetInfoBase = {
  id?: string;
  name?: string;
  path?: string;
  objectKey?: string;
  skillAssetResourceType?: SkillAssetResourceTypeEnum;
  uploadStatus?: UploadStatusEnum;
  size?: number;
};

export type SkillVersionInfoResponse = {
  version?: number;
  mainSkillMD?: SkillAssetInfoBase;
  status?: StatusEnum;
  skillAssets?: Array<SkillAssetInfoBase>;
  resourceId?: string;
};

export type RSkillInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: SkillInfoResponse;
};

export type ResourceInteractionInfoBase = {
  readCount?: number;
  likeCount?: number;
  scoreCount?: number;
  scoreTotal?: number;
};

export type ResourceItemResponse = {
  resourceName?: string;
  resourceType?: ResourceTypeEnum;
  ownerId?: string;
  preview?: string;
  size?: number;
  resourceId?: string;
  ownerInfo?: UserDisplayBase;
  resourceInteractionInfo?: ResourceInteractionInfoBase;
  currentTags?: {
    [key: string]: string;
  };
  currentActions?: Array<ItemsEnum>;
  overrideGrantedActions?: Array<ItemsEnum>;
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
};

export type SkillInfoBase = {
  name?: string;
  description?: string;
  version?: number;
  sourceType?: SourceTypeEnum;
};

export type SkillInfoResponse = {
  resourceInfo?: ResourceItemResponse;
  skillInfo?: SkillInfoBase;
};

export type UserDisplayBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: IdentityTypeEnum;
};

export type SkillAssetDeleteRequest = {
  resourceId: string;
  draftVersion?: number;
  assetIds: Array<string>;
};

export type SkillCreateRequest = {
  title: string;
  name?: string;
  description?: string;
  sourceType?: SourceTypeEnum;
};

export type RString = {
  code?: number;
  key?: string;
  msg?: string;
  data?: string;
};

export type SkillUpdateRequest = {
  resourceId?: string;
  name?: string;
  description?: string;
};

export const SkillAssetResourceTypeEnum = {
  MD: 'MD',
  PYTHON_SCRIPT: 'PYTHON_SCRIPT',
  TEXT: 'TEXT',
  JSON: 'JSON',
  YAML: 'YAML',
  TOML: 'TOML',
} as const;

export type SkillAssetResourceTypeEnum =
  (typeof SkillAssetResourceTypeEnum)[keyof typeof SkillAssetResourceTypeEnum];

export const UploadStatusEnum = { UPLOADING: 'UPLOADING', AVAILABLE: 'AVAILABLE' } as const;

export type UploadStatusEnum = (typeof UploadStatusEnum)[keyof typeof UploadStatusEnum];

export const StatusEnum = { DRAFT: 'DRAFT', PUBLISHED: 'PUBLISHED' } as const;

export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];

export const ResourceTypeEnum = {
  NOTE: 'NOTE',
  PDF: 'PDF',
  DOC: 'DOC',
  DOCX: 'DOCX',
  PPT: 'PPT',
  PPTX: 'PPTX',
  XLS: 'XLS',
  XLSX: 'XLSX',
  SKILL: 'SKILL',
  AGENT: 'AGENT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ResourceTypeEnum = (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];

export const ItemsEnum = {
  DISCOVER: 'DISCOVER',
  VIEW: 'VIEW',
  EDIT: 'EDIT',
  DOWNLOAD_WATERMARK: 'DOWNLOAD_WATERMARK',
  DOWNLOAD_ORIGINAL: 'DOWNLOAD_ORIGINAL',
} as const;

export type ItemsEnum = (typeof ItemsEnum)[keyof typeof ItemsEnum];

export const SourceTypeEnum = { BY_AGENT: 'BY_AGENT', MANUAL: 'MANUAL' } as const;

export type SourceTypeEnum = (typeof SourceTypeEnum)[keyof typeof SourceTypeEnum];

export const IdentityTypeEnum = {
  1: '1',
  2: '2',
  3: '3',
} as const;

export type IdentityTypeEnum = (typeof IdentityTypeEnum)[keyof typeof IdentityTypeEnum];

export type PublishSkillVersionData = {
  body: SkillVersionPublishRequest;
  path?: never;
  query?: never;
  url: '/skill/publishSkillVersion';
};

export type PublishSkillVersionResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type PublishSkillVersionResponse =
  PublishSkillVersionResponses[keyof PublishSkillVersionResponses];

export type InitUploadSkillAssetsData = {
  body: SkillAssetUploadInitRequest;
  path?: never;
  query?: never;
  url: '/skill/initUploadSkillAssets';
};

export type InitUploadSkillAssetsResponses = {
  /**
   * OK
   */
  200: RSkillAssetUploadInitResponse;
};

export type InitUploadSkillAssetsResponse =
  InitUploadSkillAssetsResponses[keyof InitUploadSkillAssetsResponses];

export type GetSkillVersionInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    version: number;
  };
  url: '/skill/getSkillVersionInfo';
};

export type GetSkillVersionInfoResponses = {
  /**
   * OK
   */
  200: RSkillVersionInfoResponse;
};

export type GetSkillVersionInfoResponse =
  GetSkillVersionInfoResponses[keyof GetSkillVersionInfoResponses];

export type GetSkillInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
  };
  url: '/skill/getSkillInfo';
};

export type GetSkillInfoResponses = {
  /**
   * OK
   */
  200: RSkillInfoResponse;
};

export type GetSkillInfoResponse = GetSkillInfoResponses[keyof GetSkillInfoResponses];

export type DeleteSkillAssetsData = {
  body: SkillAssetDeleteRequest;
  path?: never;
  query?: never;
  url: '/skill/deleteSkillAssets';
};

export type DeleteSkillAssetsResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteSkillAssetsResponse =
  DeleteSkillAssetsResponses[keyof DeleteSkillAssetsResponses];

export type CreateSkillData = {
  body: SkillCreateRequest;
  path?: never;
  query?: never;
  url: '/skill/createSkill';
};

export type CreateSkillResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateSkillResponse = CreateSkillResponses[keyof CreateSkillResponses];

export type UpdateSkillInfoData = {
  body: SkillUpdateRequest;
  path?: never;
  query?: never;
  url: '/skill/changeSkillInfo';
};

export type UpdateSkillInfoResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateSkillInfoResponse = UpdateSkillInfoResponses[keyof UpdateSkillInfoResponses];
