// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/docs/proxy/ai-asset` | (string & {});
};

export type AiResourceVersionPublishRequest = {
  resourceId: string;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type AssetUploadInitRequest = {
  resourceId: string;
  draftVersion: number;
  assets: Array<AssetUploadRequest>;
};

export type AssetUploadRequest = {
  name: string;
  path: string;
  assetResourceType: AssetResourceTypeEnum;
  md5?: string;
  expectedSize?: number;
};

export type AssetUploadInitResponse = {
  resourceId?: string;
  version?: number;
  assetUploadTickets?: Array<AssetUploadTicket>;
};

export type AssetUploadTicket = {
  assetId?: string;
  path?: string;
  name?: string;
  objectKey?: string;
  putUrl?: string;
  callbackHeader?: string;
  flashUploaded?: boolean;
};

export type RassetUploadInitResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: AssetUploadInitResponse;
};

export type AssetInfoBase = {
  id?: string;
  name?: string;
  path?: string;
  objectKey?: string;
  assetResourceType?: AssetResourceTypeEnum;
  uploadStatus?: UploadStatusEnum;
  size?: number;
};

export type RSkillVersionBundleInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: SkillVersionBundleInfoResponse;
};

export type SkillVersionBundleInfoResponse = {
  version?: number;
  status?: StatusEnum;
  assets?: Array<AssetInfoBase>;
  resourceId?: string;
};

export type AiResourceInfoBase = {
  name?: string;
  description?: string;
  version?: number;
  sourceType?: SourceTypeEnum;
};

export type MarketSaleInfoResponse = {
  reviewActions?: Array<ItemsEnum>;
  reviewContentPercentage?: number;
  marketSaleTiers?: Array<MarketSaleTierResponse>;
  status?: StatusEnum2;
  offerVersion?: number;
  auditMessage?: string;
  auditAt?: string;
};

export type MarketSaleTierResponse = {
  offerId?: string;
  grantedActions?: Array<ItemsEnum>;
  price?: number;
};

export type RSkillResourceInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: SkillResourceInfoResponse;
};

export type ResourceInteractionInfoBase = {
  readCount?: number;
  likeCount?: number;
  scoreCount?: number;
  scoreTotal?: number;
  favoriteCount?: number;
  commentCount?: number;
};

export type ResourceItemResponse = {
  resourceName?: string;
  resourceType?: ResourceTypeEnum;
  ownerId?: string;
  preview?: string;
  size?: number;
  resourceInteractionInfo?: ResourceInteractionInfoBase;
  resourceId?: string;
  ownerInfo?: UserDisplayBase;
  currentTags?: {
    [key: string]: TagInfoBase;
  };
  currentActions?: Array<ItemsEnum>;
  overrideGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
  specifiedUsersGrantedActions?: {
    [key: string]: Array<ItemsEnum>;
  };
  marketSaleInfos?: {
    [key: string]: MarketSaleInfoResponse;
  };
};

export type SkillResourceInfoResponse = {
  resourceInfo?: ResourceItemResponse;
  skillInfo?: AiResourceInfoBase;
};

export type TagInfoBase = {
  groupId?: string;
  tagName?: string;
  tagDesc?: string;
  tagIcon?: string;
  tagColor?: string;
  tagCreator?: string;
  isPath?: boolean;
};

export type UserDisplayBase = {
  nickname?: string;
  realName?: string;
  avatar?: string;
  identityType?: IdentityTypeEnum;
};

export type AiResourceForkRequest = {
  resourceId: string;
  forkedResourceVersion?: number;
  forkedResourceName?: string;
};

export type RString = {
  code?: number;
  key?: string;
  msg?: string;
  data?: string;
};

export type AssetDeleteRequest = {
  resourceId: string;
  draftVersion: number;
  assetIds: Array<string>;
};

export type AiResourceCreateRequest = {
  title: string;
  name?: string;
  description?: string;
  sourceType?: SourceTypeEnum;
};

export type AiResourceUpdateRequest = {
  resourceId?: string;
  name?: string;
  description?: string;
};

export type AgentMemoryPolicy = {
  enableChatMemory?: boolean;
  enablePersistenceChatMemory?: boolean;
  enableChatMemorySummary?: boolean;
  highWatermarkRatio?: number;
  lowWatermarkRatio?: number;
  summaryPrompt?: string;
  enableLongTermMemory?: boolean;
  longTermMemoryLimit?: number;
  longTermMemoryScoreThreshold?: number;
};

export type AgentModelPolicy = {
  defaultModelId?: string;
  defaultProviderId?: string;
  allowRequestOverride?: boolean;
};

export type AgentSpecInfoBase = {
  systemPrompt?: string;
  autoGenerateTitle?: boolean;
  modelPolicy?: AgentModelPolicy;
  toolAndSkillPolicy?: AgentToolAndSkillPolicy;
  memoryPolicy?: AgentMemoryPolicy;
};

export type AgentSpecUpdateRequest = {
  resourceId: string;
  draftVersion: number;
  spec: AgentSpecInfoBase;
};

export type AgentToolAndSkillPolicy = {
  enableUseTool?: boolean;
  allowToolNames?: Array<string>;
  denyToolNames?: Array<string>;
  enableUseSkill?: boolean;
  onDemandSkillIds?: Array<string>;
  forceEnabledSkillIds?: Array<string>;
};

export type AgentVersionBundleInfoResponse = {
  version?: number;
  status?: StatusEnum;
  assets?: Array<AssetInfoBase>;
  resourceId?: string;
  spec?: AgentSpecInfoBase;
};

export type RAgentVersionBundleInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: AgentVersionBundleInfoResponse;
};

export type AgentResourceInfoResponse = {
  resourceInfo?: ResourceItemResponse;
  agentInfo?: AiResourceInfoBase;
};

export type RAgentResourceInfoResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: AgentResourceInfoResponse;
};

export const AssetResourceTypeEnum = {
  MD: 'MD',
  PYTHON_SCRIPT: 'PYTHON_SCRIPT',
  TEXT: 'TEXT',
  JSON: 'JSON',
  YAML: 'YAML',
  TOML: 'TOML',
} as const;

export type AssetResourceTypeEnum =
  (typeof AssetResourceTypeEnum)[keyof typeof AssetResourceTypeEnum];

export const UploadStatusEnum = { UPLOADING: 'UPLOADING', AVAILABLE: 'AVAILABLE' } as const;

export type UploadStatusEnum = (typeof UploadStatusEnum)[keyof typeof UploadStatusEnum];

export const StatusEnum = { DRAFT: 'DRAFT', PUBLISHED: 'PUBLISHED' } as const;

export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];

export const SourceTypeEnum = { BY_AGENT: 'BY_AGENT', MANUAL: 'MANUAL' } as const;

export type SourceTypeEnum = (typeof SourceTypeEnum)[keyof typeof SourceTypeEnum];

export const ItemsEnum = {
  DISCOVER: 'DISCOVER',
  VIEW: 'VIEW',
  LOAD: 'LOAD',
  EDIT: 'EDIT',
  INLINE_COMMENT: 'INLINE_COMMENT',
  DOWNLOAD_WATERMARK: 'DOWNLOAD_WATERMARK',
  DOWNLOAD_ORIGINAL: 'DOWNLOAD_ORIGINAL',
  FORK: 'FORK',
  COMMENT: 'COMMENT',
} as const;

export type ItemsEnum = (typeof ItemsEnum)[keyof typeof ItemsEnum];

export const StatusEnum2 = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
  BANNED: 'BANNED',
  OFF_SHELF: 'OFF_SHELF',
} as const;

export type StatusEnum2 = (typeof StatusEnum2)[keyof typeof StatusEnum2];

export const ResourceTypeEnum = {
  NOTE: 'NOTE',
  DRAWIO: 'DRAWIO',
  PDF: 'PDF',
  DOC: 'DOC',
  DOCX: 'DOCX',
  PPT: 'PPT',
  PPTX: 'PPTX',
  XLS: 'XLS',
  XLSX: 'XLSX',
  SKILL: 'SKILL',
  AGENT: 'AGENT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ResourceTypeEnum = (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];

export const IdentityTypeEnum = {
  1: '1',
  2: '2',
  3: '3',
} as const;

export type IdentityTypeEnum = (typeof IdentityTypeEnum)[keyof typeof IdentityTypeEnum];

export type PublishSkillVersionData = {
  body: AiResourceVersionPublishRequest;
  path?: never;
  query?: never;
  url: '/skill/publishSkillVersion';
};

export type PublishSkillVersionResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type PublishSkillVersionResponse =
  PublishSkillVersionResponses[keyof PublishSkillVersionResponses];

export type InitUploadSkillAssetsData = {
  body: AssetUploadInitRequest;
  path?: never;
  query?: never;
  url: '/skill/initUploadSkillAssets';
};

export type InitUploadSkillAssetsResponses = {
  /**
   * OK
   */
  200: RassetUploadInitResponse;
};

export type InitUploadSkillAssetsResponse =
  InitUploadSkillAssetsResponses[keyof InitUploadSkillAssetsResponses];

export type GetSkillVersionBundleInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    version: number;
  };
  url: '/skill/getSkillVersionBundleInfo';
};

export type GetSkillVersionBundleInfoResponses = {
  /**
   * OK
   */
  200: RSkillVersionBundleInfoResponse;
};

export type GetSkillVersionBundleInfoResponse =
  GetSkillVersionBundleInfoResponses[keyof GetSkillVersionBundleInfoResponses];

export type GetSkillInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    targetVersion?: number;
  };
  url: '/skill/getSkillInfo';
};

export type GetSkillInfoResponses = {
  /**
   * OK
   */
  200: RSkillResourceInfoResponse;
};

export type GetSkillInfoResponse = GetSkillInfoResponses[keyof GetSkillInfoResponses];

export type ForkSkillData = {
  body: AiResourceForkRequest;
  path?: never;
  query?: never;
  url: '/skill/forkSkill';
};

export type ForkSkillResponses = {
  /**
   * OK
   */
  200: RString;
};

export type ForkSkillResponse = ForkSkillResponses[keyof ForkSkillResponses];

export type DeleteSkillAssetsData = {
  body: AssetDeleteRequest;
  path?: never;
  query?: never;
  url: '/skill/deleteSkillAssets';
};

export type DeleteSkillAssetsResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteSkillAssetsResponse =
  DeleteSkillAssetsResponses[keyof DeleteSkillAssetsResponses];

export type CreateSkillData = {
  body: AiResourceCreateRequest;
  path?: never;
  query?: never;
  url: '/skill/createSkill';
};

export type CreateSkillResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateSkillResponse = CreateSkillResponses[keyof CreateSkillResponses];

export type UpdateSkillInfoData = {
  body: AiResourceUpdateRequest;
  path?: never;
  query?: never;
  url: '/skill/changeSkillInfo';
};

export type UpdateSkillInfoResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateSkillInfoResponse = UpdateSkillInfoResponses[keyof UpdateSkillInfoResponses];

export type UpdateAgentSpecData = {
  body: AgentSpecUpdateRequest;
  path?: never;
  query?: never;
  url: '/agent/updateAgentSpec';
};

export type UpdateAgentSpecResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateAgentSpecResponse = UpdateAgentSpecResponses[keyof UpdateAgentSpecResponses];

export type PublishAgentVersionData = {
  body: AiResourceVersionPublishRequest;
  path?: never;
  query?: never;
  url: '/agent/publishAgentVersion';
};

export type PublishAgentVersionResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type PublishAgentVersionResponse =
  PublishAgentVersionResponses[keyof PublishAgentVersionResponses];

export type InitUploadAgentAssetsData = {
  body: AssetUploadInitRequest;
  path?: never;
  query?: never;
  url: '/agent/initUploadAgentAssets';
};

export type InitUploadAgentAssetsResponses = {
  /**
   * OK
   */
  200: RassetUploadInitResponse;
};

export type InitUploadAgentAssetsResponse =
  InitUploadAgentAssetsResponses[keyof InitUploadAgentAssetsResponses];

export type GetAgentVersionBundleInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    version: number;
  };
  url: '/agent/getAgentVersionBundleInfo';
};

export type GetAgentVersionBundleInfoResponses = {
  /**
   * OK
   */
  200: RAgentVersionBundleInfoResponse;
};

export type GetAgentVersionBundleInfoResponse =
  GetAgentVersionBundleInfoResponses[keyof GetAgentVersionBundleInfoResponses];

export type GetAgentInfoData = {
  body?: never;
  path?: never;
  query: {
    resourceId: string;
    targetVersion?: number;
  };
  url: '/agent/getAgentInfo';
};

export type GetAgentInfoResponses = {
  /**
   * OK
   */
  200: RAgentResourceInfoResponse;
};

export type GetAgentInfoResponse = GetAgentInfoResponses[keyof GetAgentInfoResponses];

export type ForkAgentData = {
  body: AiResourceForkRequest;
  path?: never;
  query?: never;
  url: '/agent/forkAgent';
};

export type ForkAgentResponses = {
  /**
   * OK
   */
  200: RString;
};

export type ForkAgentResponse = ForkAgentResponses[keyof ForkAgentResponses];

export type DeleteAgentAssetsData = {
  body: AssetDeleteRequest;
  path?: never;
  query?: never;
  url: '/agent/deleteAgentAssets';
};

export type DeleteAgentAssetsResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type DeleteAgentAssetsResponse =
  DeleteAgentAssetsResponses[keyof DeleteAgentAssetsResponses];

export type CreateAgentData = {
  body: AiResourceCreateRequest;
  path?: never;
  query?: never;
  url: '/agent/createAgent';
};

export type CreateAgentResponses = {
  /**
   * OK
   */
  200: RString;
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type UpdateAgentInfoData = {
  body: AiResourceUpdateRequest;
  path?: never;
  query?: never;
  url: '/agent/changeAgentInfo';
};

export type UpdateAgentInfoResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type UpdateAgentInfoResponse = UpdateAgentInfoResponses[keyof UpdateAgentInfoResponses];
