// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://172.28.0.22:19902' | (string & {});
};

export type MailSendDto = {
  toEmail: string;
  subject: string;
  content: string;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type SysOperLogDto = {
  title?: string;
  businessType?: number;
  method?: string;
  reqMethod?: string;
  operUserId?: number;
  operUrl?: string;
  operIp?: string;
  operParam?: string;
  jsonResult?: string;
  status?: number;
  errorMsg?: string;
  operTime?: string;
  costTime?: number;
};

export type RBoolean = {
  code?: number;
  key?: string;
  msg?: string;
  data?: boolean;
};

/**
 * 用户反馈传输对象
 */
export type FeedbackRequest = {
  content: string;
  contact?: string;
  browser?: string;
  type: TypeEnum;
};

export const TypeEnum = {
  BUG_REPORT: 'BUG_REPORT',
  SUGGESTION: 'SUGGESTION',
  CONSULTATION: 'CONSULTATION',
  COMPLAINT: 'COMPLAINT',
  OTHER: 'OTHER',
} as const;

export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];

export type SendMailData = {
  body: MailSendDto;
  path?: never;
  query?: never;
  url: '/system/mail/send';
};

export type SendMailResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type SendMailResponse = SendMailResponses[keyof SendMailResponses];

export type SaveData = {
  body: SysOperLogDto;
  path?: never;
  query?: never;
  url: '/system/log/save';
};

export type SaveResponses = {
  /**
   * OK
   */
  200: RBoolean;
};

export type SaveResponse = SaveResponses[keyof SaveResponses];

export type CreateFeedbackData = {
  body: FeedbackRequest;
  path?: never;
  query?: never;
  url: '/system/feedback/addFeedback';
};

export type CreateFeedbackResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type CreateFeedbackResponse = CreateFeedbackResponses[keyof CreateFeedbackResponses];
