// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/docs/proxy/system` | (string & {});
};

export type MailSendDto = {
  toEmail: string;
  subject: string;
  content: string;
};

export type RVoid = {
  code?: number;
  key?: string;
  msg?: string;
  data?: {
    [key: string]: unknown;
  };
};

export type SysOperLogDto = {
  title?: string;
  businessType?: number;
  method?: string;
  reqMethod?: string;
  operUserId?: number;
  operUrl?: string;
  operIp?: string;
  operParam?: string;
  jsonResult?: string;
  status?: number;
  errorMsg?: string;
  operTime?: string;
  costTime?: number;
};

export type RBoolean = {
  code?: number;
  key?: string;
  msg?: string;
  data?: boolean;
};

export type FeedbackRequest = {
  content?: string;
  contact?: string;
  browser?: string;
  type?: TypeEnum;
};

export type PageRSysOperLogResponse = {
  list?: Array<SysOperLogResponse>;
  total?: number;
  page?: number;
  size?: number;
  totalPage?: number;
};

export type RPageRSysOperLogResponse = {
  code?: number;
  key?: string;
  msg?: string;
  data?: PageRSysOperLogResponse;
};

export type SysOperLogResponse = {
  title?: string;
  businessType?: number;
  method?: string;
  reqMethod?: string;
  operUserId?: number;
  operUrl?: string;
  operIp?: string;
  operParam?: string;
  jsonResult?: string;
  status?: number;
  errorMsg?: string;
  operTime?: string;
  costTime?: number;
};

export const TypeEnum = {
  BUG_REPORT: 'BUG_REPORT',
  SUGGESTION: 'SUGGESTION',
  CONSULTATION: 'CONSULTATION',
  COMPLAINT: 'COMPLAINT',
  OTHER: 'OTHER',
} as const;

export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];

export type SendMailData = {
  body: MailSendDto;
  path?: never;
  query?: never;
  url: '/system/mail/send';
};

export type SendMailResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type SendMailResponse = SendMailResponses[keyof SendMailResponses];

export type SaveLogData = {
  body: SysOperLogDto;
  path?: never;
  query?: never;
  url: '/system/log/saveLog';
};

export type SaveLogResponses = {
  /**
   * OK
   */
  200: RBoolean;
};

export type SaveLogResponse = SaveLogResponses[keyof SaveLogResponses];

export type CreateFeedbackData = {
  body: FeedbackRequest;
  path?: never;
  query?: never;
  url: '/system/feedback/addFeedback';
};

export type CreateFeedbackResponses = {
  /**
   * OK
   */
  200: RVoid;
};

export type CreateFeedbackResponse = CreateFeedbackResponses[keyof CreateFeedbackResponses];

export type ListLogsData = {
  body?: never;
  path?: never;
  query: {
    operUrl: string;
    operUserId: number;
    startTime: string;
    endTime: string;
    status: number;
    page: number;
    size: number;
  };
  url: '/system/log/listLogs';
};

export type ListLogsResponses = {
  /**
   * OK
   */
  200: RPageRSysOperLogResponse;
};

export type ListLogsResponse = ListLogsResponses[keyof ListLogsResponses];
