// This file is auto-generated by @hey-api/openapi-ts

export type {
  ClientOptions,
  FudanUisTaskResultDto,
  GetTaskStatusData,
  GetTaskStatusResponse,
  GetTaskStatusResponses,
  RFudanUisTaskResultDto,
} from './types.gen';
