/** 前端网络/传输层错误码（10–99） */
export const FRONTEND_NETWORK_ERROR = {
  TIMEOUT: 10,
  NETWORK: 11,
  CANCELED: 12,
  BAD_REQUEST: 13,
  SERVER: 14,
  HTTP: 15,
  UNKNOWN: 99,
} as const;

/** 前端 Service/客户端校验错误码（100–999） */
export const FRONTEND_CLIENT_ERROR = {
  VALIDATION: 100,
  UNKNOWN: 999,
  IMAGE_FILE_TOO_LARGE: 101,
  DOCUMENT_FILE_TOO_LARGE: 102,
  DOCUMENT_UNSUPPORTED_TYPE: 103,
  FILE_EXTENSION_REQUIRED: 104,
  IMAGE_ONLY: 105,
  GROUP_ID_REQUIRED: 106,
  NOTE_CREATE_RESOURCE_ID_MISSING: 107,
  CHAT_CREATE_SESSION_FAILED: 108,
  CHAT_RENAME_SESSION_FAILED: 109,
  DOCUMENT_UPLOAD_INIT_EMPTY: 110,
  DOCUMENT_UPLOAD_URL_INVALID: 111,
  DRIVE_PERSONAL_ROOT_NOT_FOUND: 112,
  DRIVE_NODE_NOT_FOUND: 113,
  DRIVE_TRASH_TAG_NOT_FOUND: 114,
  DRIVE_RESOURCE_TAG_INFO_MISSING: 115,
  DRIVE_UNSUPPORTED_ROOT: 116,
  DRIVE_TARGET_UNSUPPORTED_DROP: 117,
  DRIVE_NODE_UNSUPPORTED_MOVE: 118,
  DRIVE_NODE_UNSUPPORTED_DELETE: 119,
  DRIVE_LINK_UNSUPPORTED_RENAME: 120,
  DRIVE_NODE_UNSUPPORTED_RENAME: 121,
  DRIVE_UNSUPPORTED_CREATE_TYPE: 122,
  DRIVE_CREATE_FOLDER_ONLY: 123,
  GROUP_INFO_FETCH_FAILED: 124,
  GROUP_WALLET_FETCH_FAILED: 125,
  GROUP_RES_CONFIG_FETCH_FAILED: 126,
  GROUP_RES_CONFIG_INVALID: 127,
  GROUP_CREATE_FAILED: 128,
  GROUP_ROLE_FETCH_FAILED: 129,
  NOTE_NOT_FOUND: 130,
  WALLET_VOUCHER_CODE_INVALID: 131,
  WALLET_VOUCHER_USED: 132,
  WALLET_VOUCHER_INVALID: 133,
  DRIVE_LINK_MOVE_TO_PRIMARY_TAG: 134,
  SKILL_CREATE_RESOURCE_ID_MISSING: 135,
} as const;

export type FrontendNetworkErrorCode =
  (typeof FRONTEND_NETWORK_ERROR)[keyof typeof FRONTEND_NETWORK_ERROR];

export type FrontendClientErrorCode =
  (typeof FRONTEND_CLIENT_ERROR)[keyof typeof FRONTEND_CLIENT_ERROR];
